const DISCORD = "https://discord.gg/fusuVXV6a";

const members = [
  {name:"Hussein", role:"Owner", rank:"Wolf", kills:3554, skill:9.8, status:"ONLINE"},
  {name:"Xiris", role:"Semi owner", rank:"MEMBER", kills:8200, skill:8.4, status:"ONLINE"},
  {name:"PLAYER 03", role:"MEMBER", rank:"MEMBER", kills:6400, skill:7.2, status:"AWAY"},
  {name:"PLAYER 04", role:"MEMBER", rank:"MEMBER", kills:5100, skill:6.8, status:"AWAY"},
  {name:"PLAYER 05", role:"MEMBER", rank:"MEMBER", kills:4700, skill:6.6, status:"AWAY"},
  {name:"PLAYER 06", role:"MEMBER", rank:"MEMBER", kills:3900, skill:6.1, status:"AWAY"}
];

const rules = [
  {title:"GENERAL CONDUCT", text:"Red Vortex is a community first. Keep the server and clan environment respectful and usable for everyone.", bullets:["Treat all clan members with respect.","No racism, harassment, or unnecessary toxicity.","No spam or excessive pinging.","No NSFW content.","No advertising other servers without permission.","Follow Discord Terms of Service and server rules."]},
  {title:"TSB GAMEPLAY", text:"Competition is the point. Cheating is not. Keep gameplay legitimate and respect clan events.", bullets:["No exploiting or cheating.","No intentionally ruining clan matches.","Respect 1v1s and clan events.","Don't fake being a clan staff member.","Follow instructions from clan staff during events."]},
  {title:"CLAN REQUIREMENTS", text:"Red Vortex has a clear entry bar so everyone joining understands the standard.", bullets:["Minimum 3,000 kills.","Minimum 6+ Skill Rating.","Be able to prove your stats if requested.","Staff may test your skill if needed."]},
  {title:"PUNISHMENTS", text:"Staff can enforce rules based on severity and context. Serious violations may skip steps.", bullets:["Warning → Mute → Kick → Ban.","Severe offenses may skip straight to a ban.","Staff decisions should be respected.","Report problems to staff instead of escalating drama."]}
];

const faqs = [
  ["How do I join Red Vortex?","Meet the 3,000+ kills and 6+ Skill Rating requirements, then join the Discord and follow the recruitment process."],
  ["Do I need proof of my stats?","Be ready to show your stats if staff asks. This helps keep the requirements fair."],
  ["Can staff test my gameplay?","Yep. Staff may test your gameplay when needed as part of checking skill."],
  ["Are exploits or cheats allowed?","No. Exploiting and cheating are against the clan rules."],
  ["Where is the clan community?","The main Red Vortex community is on Discord. Use the Discord buttons on this site to join."],
  ["Can I suggest a change to the clan?","Absolutely. Bring suggestions to the appropriate staff channel in Discord and keep it constructive."]
];

const $ = (s, p=document) => p.querySelector(s);
const $$ = (s, p=document) => [...p.querySelectorAll(s)];

window.addEventListener("load", () => {
  const bootText = $("#bootText");
  const messages = ["SYNCING...", "LOADING ROSTER...", "VERIFYING PROTOCOLS...", "SYSTEM READY."];
  let n=0;
  const timer=setInterval(()=>{ bootText.textContent=messages[n++]; if(n===messages.length){clearInterval(timer);setTimeout(()=>$("#boot").classList.add("hide"),500)} },500);
});

const canvas=$("#particles"), ctx=canvas.getContext("2d");
let particles=[];
function resizeCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function makeParticles(){
  particles=Array.from({length:Math.min(95,Math.floor(innerWidth/12))},()=>({
    x:Math.random()*innerWidth,y:Math.random()*innerHeight,
    r:Math.random()*1.4+.2,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18,a:Math.random()*.5+.1
  }));
}
function particleLoop(){
  ctx.clearRect(0,0,innerWidth,innerHeight);
  for(const p of particles){
    p.x+=p.vx;p.y+=p.vy;
    if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;
    ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(255,55,45,${p.a})`;ctx.fill();
  }
  requestAnimationFrame(particleLoop);
}
addEventListener("resize",()=>{resizeCanvas();makeParticles()});resizeCanvas();makeParticles();particleLoop();

const glow=$("#cursorGlow");
addEventListener("pointermove",e=>{glow.style.left=e.clientX+"px";glow.style.top=e.clientY+"px"});
$$(".magnetic").forEach(el=>{
  el.addEventListener("pointermove",e=>{
    const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.08,y=(e.clientY-r.top-r.height/2)*.08;
    el.style.transform=`translate(${x}px,${y}px)`;
  });
  el.addEventListener("pointerleave",()=>el.style.transform="");
});

const menu=$("#menuBtn"), nav=$("#nav");
menu.addEventListener("click",()=>nav.classList.toggle("open"));
$$("nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));

const observer=new IntersectionObserver(entries=>{
  entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}});
},{threshold:.08});
$$(".reveal").forEach(x=>observer.observe(x));

function memberCard(m,index){
  const initial=(m.name.replace(/[^A-Z0-9]/gi,"")[0]||"R").toUpperCase();
  return `<article class="member-card reveal visible" data-name="${m.name.toLowerCase()}" data-role="${m.rank.toLowerCase()}" data-member='${JSON.stringify(m)}'>
    <div class="member-top"><div class="member-avatar">${initial}</div><span class="member-rank">${String(index+1).padStart(2,"0")} // ${m.rank}</span></div>
    <h3>${m.name}</h3><div class="member-role">${m.role}</div>
    <div class="member-meta"><div><span>KILLS</span><b>${m.kills.toLocaleString()}</b></div><div><span>SKILL</span><b>${m.skill}</b></div></div>
    <div class="member-status">● ${m.status}</div>
  </article>`;
}
function renderRoster(){
  const q=$("#memberSearch").value.toLowerCase().trim();
  const active=$(".filter.active").dataset.filter;
  const data=members.filter(m=>(active==="all"||m.rank.toLowerCase()===active)&&(!q||m.name.toLowerCase().includes(q)||m.role.toLowerCase().includes(q)));
  $("#rosterGrid").innerHTML=data.map(memberCard).join("");
  $("#rosterEmpty").classList.toggle("hidden",data.length>0);
  $$(".member-card").forEach(card=>card.addEventListener("click",()=>openMember(JSON.parse(card.dataset.member))));
}
renderRoster();
$("#memberSearch").addEventListener("input",renderRoster);
$$(".filter").forEach(btn=>btn.addEventListener("click",()=>{$$(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderRoster()}));

function openMember(m){
  $("#modalContent").innerHTML=`<div class="modal-profile"><div class="member-avatar">${(m.name[0]||"R").toUpperCase()}</div><div><h3>${m.name}</h3><p>${m.role} // ${m.rank}</p></div></div>
  <div class="modal-stats"><div><span>KILLS</span><b>${m.kills.toLocaleString()}</b></div><div><span>SKILL RATING</span><b>${m.skill}</b></div><div><span>STATUS</span><b>${m.status}</b></div><div><span>DIVISION</span><b>TSB</b></div></div>`;
  $("#memberModal").classList.remove("hidden");
}
$$("[data-close]").forEach(x=>x.addEventListener("click",()=>$("#memberModal").classList.add("hidden")));
addEventListener("keydown",e=>{if(e.key==="Escape")$("#memberModal").classList.add("hidden")});

$("#rulesNav").innerHTML=rules.map((r,i)=>`<button class="rule-tab ${i===0?"active":""}" data-rule="${i}"><span>${String(i+1).padStart(2,"0")}</span>${r.title}<span>›</span></button>`).join("");
function renderRule(i){
 const r=rules[i];
 $("#rulesContent").innerHTML=`<div class="rule-pane"><span class="pane-no">RULE ${String(i+1).padStart(2,"0")}</span><h3>${r.title}</h3><p>${r.text}</p><div class="rule-bullets">${r.bullets.map(x=>`<div class="rule-bullet"><i>◆</i><span>${x}</span></div>`).join("")}</div></div>`;
}
renderRule(0);
$$(".rule-tab").forEach(btn=>btn.addEventListener("click",()=>{$$(".rule-tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderRule(+btn.dataset.rule)}));

$("#faq").innerHTML=faqs.map((f,i)=>`<div class="faq-item ${i===0?"open":""}"><button class="faq-q">${f[0]}<b>${i===0?"−":"+"}</b></button><div class="faq-a"><p>${f[1]}</p></div></div>`).join("");
$$(".faq-q").forEach(q=>q.addEventListener("click",()=>{const item=q.parentElement;item.classList.toggle("open");q.querySelector("b").textContent=item.classList.contains("open")?"−":"+"}));

const terminalLines=[
  ["[RV]","BOOT SEQUENCE","ok"],["[RV]","DISCORD LINK VERIFIED","ok"],["[RV]","MIN KILLS: 3000",""],["[RV]","MIN SKILL: 6+",""],["[RV]","CHEAT PROTOCOL: BLOCKED","ok"],["[RV]","ROSTER DATABASE: READY","ok"],["[RV]","COMMUNITY STATUS: ONLINE","ok"],["[RV]","WELCOME TO RED VORTEX.","dim"]
];
const terminal=$("#terminalLines");
terminalLines.forEach((line,i)=>{const d=document.createElement("div");d.innerHTML=`<b>${line[0]}</b> ${line[1]} <span class="${line[2]}">${line[2]==="ok"?"[OK]":""}</span>`;d.style.opacity="0";terminal.appendChild(d);setTimeout(()=>d.style.opacity="1",500+i*250)});

const topBtn=$("#topBtn");
addEventListener("scroll",()=>topBtn.classList.toggle("show",scrollY>700));
topBtn.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));

const counters=$$(".big-stat strong[data-count]");
const countObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const el=e.target,end=+el.dataset.count,start=0,duration=1100,t0=performance.now();function tick(t){const p=Math.min(1,(t-t0)/duration),v=Math.floor((1-Math.pow(1-p,3))*end);el.textContent=v.toLocaleString()+(end===6?"+":"+");if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);countObs.unobserve(el)}}),{threshold:.5});
counters.forEach(x=>countObs.observe(x));

document.addEventListener("keydown",e=>{
  if(e.key.toLowerCase()==="j"&&e.ctrlKey){e.preventDefault();location.hash="#recruitment"}
});

const reduce=matchMedia("(prefers-reduced-motion: reduce)");
if(reduce.matches){
  document.documentElement.style.scrollBehavior="auto";
  $$(".reveal").forEach(x=>{x.style.opacity=1;x.style.transform="none"});
}

/* EXPANSION CONFIG SLOTS — ready for future clan features */
const RV_CONFIG_001 = { enabled: true, slot: 1, label: 'RED VORTEX SYSTEM 001' };
const RV_CONFIG_002 = { enabled: true, slot: 2, label: 'RED VORTEX SYSTEM 002' };
const RV_CONFIG_003 = { enabled: true, slot: 3, label: 'RED VORTEX SYSTEM 003' };
const RV_CONFIG_004 = { enabled: true, slot: 4, label: 'RED VORTEX SYSTEM 004' };
const RV_CONFIG_005 = { enabled: true, slot: 5, label: 'RED VORTEX SYSTEM 005' };
const RV_CONFIG_006 = { enabled: true, slot: 6, label: 'RED VORTEX SYSTEM 006' };
const RV_CONFIG_007 = { enabled: true, slot: 7, label: 'RED VORTEX SYSTEM 007' };
const RV_CONFIG_008 = { enabled: true, slot: 8, label: 'RED VORTEX SYSTEM 008' };
const RV_CONFIG_009 = { enabled: true, slot: 9, label: 'RED VORTEX SYSTEM 009' };
const RV_CONFIG_010 = { enabled: true, slot: 10, label: 'RED VORTEX SYSTEM 010' };
const RV_CONFIG_011 = { enabled: true, slot: 11, label: 'RED VORTEX SYSTEM 011' };
const RV_CONFIG_012 = { enabled: true, slot: 12, label: 'RED VORTEX SYSTEM 012' };
const RV_CONFIG_013 = { enabled: true, slot: 13, label: 'RED VORTEX SYSTEM 013' };
const RV_CONFIG_014 = { enabled: true, slot: 14, label: 'RED VORTEX SYSTEM 014' };
const RV_CONFIG_015 = { enabled: true, slot: 15, label: 'RED VORTEX SYSTEM 015' };
const RV_CONFIG_016 = { enabled: true, slot: 16, label: 'RED VORTEX SYSTEM 016' };
const RV_CONFIG_017 = { enabled: true, slot: 17, label: 'RED VORTEX SYSTEM 017' };
const RV_CONFIG_018 = { enabled: true, slot: 18, label: 'RED VORTEX SYSTEM 018' };
const RV_CONFIG_019 = { enabled: true, slot: 19, label: 'RED VORTEX SYSTEM 019' };
const RV_CONFIG_020 = { enabled: true, slot: 20, label: 'RED VORTEX SYSTEM 020' };
const RV_CONFIG_021 = { enabled: true, slot: 21, label: 'RED VORTEX SYSTEM 021' };
const RV_CONFIG_022 = { enabled: true, slot: 22, label: 'RED VORTEX SYSTEM 022' };
const RV_CONFIG_023 = { enabled: true, slot: 23, label: 'RED VORTEX SYSTEM 023' };
const RV_CONFIG_024 = { enabled: true, slot: 24, label: 'RED VORTEX SYSTEM 024' };
const RV_CONFIG_025 = { enabled: true, slot: 25, label: 'RED VORTEX SYSTEM 025' };
const RV_CONFIG_026 = { enabled: true, slot: 26, label: 'RED VORTEX SYSTEM 026' };
const RV_CONFIG_027 = { enabled: true, slot: 27, label: 'RED VORTEX SYSTEM 027' };
const RV_CONFIG_028 = { enabled: true, slot: 28, label: 'RED VORTEX SYSTEM 028' };
const RV_CONFIG_029 = { enabled: true, slot: 29, label: 'RED VORTEX SYSTEM 029' };
const RV_CONFIG_030 = { enabled: true, slot: 30, label: 'RED VORTEX SYSTEM 030' };
const RV_CONFIG_031 = { enabled: true, slot: 31, label: 'RED VORTEX SYSTEM 031' };
const RV_CONFIG_032 = { enabled: true, slot: 32, label: 'RED VORTEX SYSTEM 032' };
const RV_CONFIG_033 = { enabled: true, slot: 33, label: 'RED VORTEX SYSTEM 033' };
const RV_CONFIG_034 = { enabled: true, slot: 34, label: 'RED VORTEX SYSTEM 034' };
const RV_CONFIG_035 = { enabled: true, slot: 35, label: 'RED VORTEX SYSTEM 035' };
const RV_CONFIG_036 = { enabled: true, slot: 36, label: 'RED VORTEX SYSTEM 036' };
const RV_CONFIG_037 = { enabled: true, slot: 37, label: 'RED VORTEX SYSTEM 037' };
const RV_CONFIG_038 = { enabled: true, slot: 38, label: 'RED VORTEX SYSTEM 038' };
const RV_CONFIG_039 = { enabled: true, slot: 39, label: 'RED VORTEX SYSTEM 039' };
const RV_CONFIG_040 = { enabled: true, slot: 40, label: 'RED VORTEX SYSTEM 040' };
const RV_CONFIG_041 = { enabled: true, slot: 41, label: 'RED VORTEX SYSTEM 041' };
const RV_CONFIG_042 = { enabled: true, slot: 42, label: 'RED VORTEX SYSTEM 042' };
const RV_CONFIG_043 = { enabled: true, slot: 43, label: 'RED VORTEX SYSTEM 043' };
const RV_CONFIG_044 = { enabled: true, slot: 44, label: 'RED VORTEX SYSTEM 044' };
const RV_CONFIG_045 = { enabled: true, slot: 45, label: 'RED VORTEX SYSTEM 045' };
const RV_CONFIG_046 = { enabled: true, slot: 46, label: 'RED VORTEX SYSTEM 046' };
const RV_CONFIG_047 = { enabled: true, slot: 47, label: 'RED VORTEX SYSTEM 047' };
const RV_CONFIG_048 = { enabled: true, slot: 48, label: 'RED VORTEX SYSTEM 048' };
const RV_CONFIG_049 = { enabled: true, slot: 49, label: 'RED VORTEX SYSTEM 049' };
const RV_CONFIG_050 = { enabled: true, slot: 50, label: 'RED VORTEX SYSTEM 050' };
const RV_CONFIG_051 = { enabled: true, slot: 51, label: 'RED VORTEX SYSTEM 051' };
const RV_CONFIG_052 = { enabled: true, slot: 52, label: 'RED VORTEX SYSTEM 052' };
const RV_CONFIG_053 = { enabled: true, slot: 53, label: 'RED VORTEX SYSTEM 053' };
const RV_CONFIG_054 = { enabled: true, slot: 54, label: 'RED VORTEX SYSTEM 054' };
const RV_CONFIG_055 = { enabled: true, slot: 55, label: 'RED VORTEX SYSTEM 055' };
const RV_CONFIG_056 = { enabled: true, slot: 56, label: 'RED VORTEX SYSTEM 056' };
const RV_CONFIG_057 = { enabled: true, slot: 57, label: 'RED VORTEX SYSTEM 057' };
const RV_CONFIG_058 = { enabled: true, slot: 58, label: 'RED VORTEX SYSTEM 058' };
const RV_CONFIG_059 = { enabled: true, slot: 59, label: 'RED VORTEX SYSTEM 059' };
const RV_CONFIG_060 = { enabled: true, slot: 60, label: 'RED VORTEX SYSTEM 060' };
const RV_CONFIG_061 = { enabled: true, slot: 61, label: 'RED VORTEX SYSTEM 061' };
const RV_CONFIG_062 = { enabled: true, slot: 62, label: 'RED VORTEX SYSTEM 062' };
const RV_CONFIG_063 = { enabled: true, slot: 63, label: 'RED VORTEX SYSTEM 063' };
const RV_CONFIG_064 = { enabled: true, slot: 64, label: 'RED VORTEX SYSTEM 064' };
const RV_CONFIG_065 = { enabled: true, slot: 65, label: 'RED VORTEX SYSTEM 065' };
const RV_CONFIG_066 = { enabled: true, slot: 66, label: 'RED VORTEX SYSTEM 066' };
const RV_CONFIG_067 = { enabled: true, slot: 67, label: 'RED VORTEX SYSTEM 067' };
const RV_CONFIG_068 = { enabled: true, slot: 68, label: 'RED VORTEX SYSTEM 068' };
const RV_CONFIG_069 = { enabled: true, slot: 69, label: 'RED VORTEX SYSTEM 069' };
const RV_CONFIG_070 = { enabled: true, slot: 70, label: 'RED VORTEX SYSTEM 070' };
const RV_CONFIG_071 = { enabled: true, slot: 71, label: 'RED VORTEX SYSTEM 071' };
const RV_CONFIG_072 = { enabled: true, slot: 72, label: 'RED VORTEX SYSTEM 072' };
const RV_CONFIG_073 = { enabled: true, slot: 73, label: 'RED VORTEX SYSTEM 073' };
const RV_CONFIG_074 = { enabled: true, slot: 74, label: 'RED VORTEX SYSTEM 074' };
const RV_CONFIG_075 = { enabled: true, slot: 75, label: 'RED VORTEX SYSTEM 075' };
const RV_CONFIG_076 = { enabled: true, slot: 76, label: 'RED VORTEX SYSTEM 076' };
const RV_CONFIG_077 = { enabled: true, slot: 77, label: 'RED VORTEX SYSTEM 077' };
const RV_CONFIG_078 = { enabled: true, slot: 78, label: 'RED VORTEX SYSTEM 078' };
const RV_CONFIG_079 = { enabled: true, slot: 79, label: 'RED VORTEX SYSTEM 079' };
const RV_CONFIG_080 = { enabled: true, slot: 80, label: 'RED VORTEX SYSTEM 080' };
const RV_CONFIG_081 = { enabled: true, slot: 81, label: 'RED VORTEX SYSTEM 081' };
const RV_CONFIG_082 = { enabled: true, slot: 82, label: 'RED VORTEX SYSTEM 082' };
const RV_CONFIG_083 = { enabled: true, slot: 83, label: 'RED VORTEX SYSTEM 083' };
const RV_CONFIG_084 = { enabled: true, slot: 84, label: 'RED VORTEX SYSTEM 084' };
const RV_CONFIG_085 = { enabled: true, slot: 85, label: 'RED VORTEX SYSTEM 085' };
const RV_CONFIG_086 = { enabled: true, slot: 86, label: 'RED VORTEX SYSTEM 086' };
const RV_CONFIG_087 = { enabled: true, slot: 87, label: 'RED VORTEX SYSTEM 087' };
const RV_CONFIG_088 = { enabled: true, slot: 88, label: 'RED VORTEX SYSTEM 088' };
const RV_CONFIG_089 = { enabled: true, slot: 89, label: 'RED VORTEX SYSTEM 089' };
const RV_CONFIG_090 = { enabled: true, slot: 90, label: 'RED VORTEX SYSTEM 090' };
const RV_CONFIG_091 = { enabled: true, slot: 91, label: 'RED VORTEX SYSTEM 091' };
const RV_CONFIG_092 = { enabled: true, slot: 92, label: 'RED VORTEX SYSTEM 092' };
const RV_CONFIG_093 = { enabled: true, slot: 93, label: 'RED VORTEX SYSTEM 093' };
const RV_CONFIG_094 = { enabled: true, slot: 94, label: 'RED VORTEX SYSTEM 094' };
const RV_CONFIG_095 = { enabled: true, slot: 95, label: 'RED VORTEX SYSTEM 095' };
const RV_CONFIG_096 = { enabled: true, slot: 96, label: 'RED VORTEX SYSTEM 096' };
const RV_CONFIG_097 = { enabled: true, slot: 97, label: 'RED VORTEX SYSTEM 097' };
const RV_CONFIG_098 = { enabled: true, slot: 98, label: 'RED VORTEX SYSTEM 098' };
const RV_CONFIG_099 = { enabled: true, slot: 99, label: 'RED VORTEX SYSTEM 099' };
const RV_CONFIG_100 = { enabled: true, slot: 100, label: 'RED VORTEX SYSTEM 100' };
const RV_CONFIG_101 = { enabled: true, slot: 101, label: 'RED VORTEX SYSTEM 101' };
const RV_CONFIG_102 = { enabled: true, slot: 102, label: 'RED VORTEX SYSTEM 102' };
const RV_CONFIG_103 = { enabled: true, slot: 103, label: 'RED VORTEX SYSTEM 103' };
const RV_CONFIG_104 = { enabled: true, slot: 104, label: 'RED VORTEX SYSTEM 104' };
const RV_CONFIG_105 = { enabled: true, slot: 105, label: 'RED VORTEX SYSTEM 105' };
const RV_CONFIG_106 = { enabled: true, slot: 106, label: 'RED VORTEX SYSTEM 106' };
const RV_CONFIG_107 = { enabled: true, slot: 107, label: 'RED VORTEX SYSTEM 107' };
const RV_CONFIG_108 = { enabled: true, slot: 108, label: 'RED VORTEX SYSTEM 108' };
const RV_CONFIG_109 = { enabled: true, slot: 109, label: 'RED VORTEX SYSTEM 109' };
const RV_CONFIG_110 = { enabled: true, slot: 110, label: 'RED VORTEX SYSTEM 110' };
const RV_CONFIG_111 = { enabled: true, slot: 111, label: 'RED VORTEX SYSTEM 111' };
const RV_CONFIG_112 = { enabled: true, slot: 112, label: 'RED VORTEX SYSTEM 112' };
const RV_CONFIG_113 = { enabled: true, slot: 113, label: 'RED VORTEX SYSTEM 113' };
const RV_CONFIG_114 = { enabled: true, slot: 114, label: 'RED VORTEX SYSTEM 114' };
const RV_CONFIG_115 = { enabled: true, slot: 115, label: 'RED VORTEX SYSTEM 115' };
const RV_CONFIG_116 = { enabled: true, slot: 116, label: 'RED VORTEX SYSTEM 116' };
const RV_CONFIG_117 = { enabled: true, slot: 117, label: 'RED VORTEX SYSTEM 117' };
const RV_CONFIG_118 = { enabled: true, slot: 118, label: 'RED VORTEX SYSTEM 118' };
const RV_CONFIG_119 = { enabled: true, slot: 119, label: 'RED VORTEX SYSTEM 119' };
const RV_CONFIG_120 = { enabled: true, slot: 120, label: 'RED VORTEX SYSTEM 120' };
const RV_CONFIG_121 = { enabled: true, slot: 121, label: 'RED VORTEX SYSTEM 121' };
const RV_CONFIG_122 = { enabled: true, slot: 122, label: 'RED VORTEX SYSTEM 122' };
const RV_CONFIG_123 = { enabled: true, slot: 123, label: 'RED VORTEX SYSTEM 123' };
const RV_CONFIG_124 = { enabled: true, slot: 124, label: 'RED VORTEX SYSTEM 124' };
const RV_CONFIG_125 = { enabled: true, slot: 125, label: 'RED VORTEX SYSTEM 125' };
const RV_CONFIG_126 = { enabled: true, slot: 126, label: 'RED VORTEX SYSTEM 126' };
const RV_CONFIG_127 = { enabled: true, slot: 127, label: 'RED VORTEX SYSTEM 127' };
const RV_CONFIG_128 = { enabled: true, slot: 128, label: 'RED VORTEX SYSTEM 128' };
const RV_CONFIG_129 = { enabled: true, slot: 129, label: 'RED VORTEX SYSTEM 129' };
const RV_CONFIG_130 = { enabled: true, slot: 130, label: 'RED VORTEX SYSTEM 130' };
const RV_CONFIG_131 = { enabled: true, slot: 131, label: 'RED VORTEX SYSTEM 131' };
const RV_CONFIG_132 = { enabled: true, slot: 132, label: 'RED VORTEX SYSTEM 132' };
const RV_CONFIG_133 = { enabled: true, slot: 133, label: 'RED VORTEX SYSTEM 133' };
const RV_CONFIG_134 = { enabled: true, slot: 134, label: 'RED VORTEX SYSTEM 134' };
const RV_CONFIG_135 = { enabled: true, slot: 135, label: 'RED VORTEX SYSTEM 135' };
const RV_CONFIG_136 = { enabled: true, slot: 136, label: 'RED VORTEX SYSTEM 136' };
const RV_CONFIG_137 = { enabled: true, slot: 137, label: 'RED VORTEX SYSTEM 137' };
const RV_CONFIG_138 = { enabled: true, slot: 138, label: 'RED VORTEX SYSTEM 138' };
const RV_CONFIG_139 = { enabled: true, slot: 139, label: 'RED VORTEX SYSTEM 139' };
const RV_CONFIG_140 = { enabled: true, slot: 140, label: 'RED VORTEX SYSTEM 140' };
const RV_CONFIG_141 = { enabled: true, slot: 141, label: 'RED VORTEX SYSTEM 141' };
const RV_CONFIG_142 = { enabled: true, slot: 142, label: 'RED VORTEX SYSTEM 142' };
const RV_CONFIG_143 = { enabled: true, slot: 143, label: 'RED VORTEX SYSTEM 143' };
const RV_CONFIG_144 = { enabled: true, slot: 144, label: 'RED VORTEX SYSTEM 144' };
const RV_CONFIG_145 = { enabled: true, slot: 145, label: 'RED VORTEX SYSTEM 145' };
const RV_CONFIG_146 = { enabled: true, slot: 146, label: 'RED VORTEX SYSTEM 146' };
const RV_CONFIG_147 = { enabled: true, slot: 147, label: 'RED VORTEX SYSTEM 147' };
const RV_CONFIG_148 = { enabled: true, slot: 148, label: 'RED VORTEX SYSTEM 148' };
const RV_CONFIG_149 = { enabled: true, slot: 149, label: 'RED VORTEX SYSTEM 149' };
const RV_CONFIG_150 = { enabled: true, slot: 150, label: 'RED VORTEX SYSTEM 150' };
const RV_CONFIG_151 = { enabled: true, slot: 151, label: 'RED VORTEX SYSTEM 151' };
const RV_CONFIG_152 = { enabled: true, slot: 152, label: 'RED VORTEX SYSTEM 152' };
const RV_CONFIG_153 = { enabled: true, slot: 153, label: 'RED VORTEX SYSTEM 153' };
const RV_CONFIG_154 = { enabled: true, slot: 154, label: 'RED VORTEX SYSTEM 154' };
const RV_CONFIG_155 = { enabled: true, slot: 155, label: 'RED VORTEX SYSTEM 155' };
const RV_CONFIG_156 = { enabled: true, slot: 156, label: 'RED VORTEX SYSTEM 156' };
const RV_CONFIG_157 = { enabled: true, slot: 157, label: 'RED VORTEX SYSTEM 157' };
const RV_CONFIG_158 = { enabled: true, slot: 158, label: 'RED VORTEX SYSTEM 158' };
const RV_CONFIG_159 = { enabled: true, slot: 159, label: 'RED VORTEX SYSTEM 159' };
const RV_CONFIG_160 = { enabled: true, slot: 160, label: 'RED VORTEX SYSTEM 160' };
const RV_CONFIG_161 = { enabled: true, slot: 161, label: 'RED VORTEX SYSTEM 161' };
const RV_CONFIG_162 = { enabled: true, slot: 162, label: 'RED VORTEX SYSTEM 162' };
const RV_CONFIG_163 = { enabled: true, slot: 163, label: 'RED VORTEX SYSTEM 163' };
const RV_CONFIG_164 = { enabled: true, slot: 164, label: 'RED VORTEX SYSTEM 164' };
const RV_CONFIG_165 = { enabled: true, slot: 165, label: 'RED VORTEX SYSTEM 165' };
const RV_CONFIG_166 = { enabled: true, slot: 166, label: 'RED VORTEX SYSTEM 166' };
const RV_CONFIG_167 = { enabled: true, slot: 167, label: 'RED VORTEX SYSTEM 167' };
const RV_CONFIG_168 = { enabled: true, slot: 168, label: 'RED VORTEX SYSTEM 168' };
const RV_CONFIG_169 = { enabled: true, slot: 169, label: 'RED VORTEX SYSTEM 169' };
const RV_CONFIG_170 = { enabled: true, slot: 170, label: 'RED VORTEX SYSTEM 170' };
const RV_CONFIG_171 = { enabled: true, slot: 171, label: 'RED VORTEX SYSTEM 171' };
const RV_CONFIG_172 = { enabled: true, slot: 172, label: 'RED VORTEX SYSTEM 172' };
const RV_CONFIG_173 = { enabled: true, slot: 173, label: 'RED VORTEX SYSTEM 173' };
const RV_CONFIG_174 = { enabled: true, slot: 174, label: 'RED VORTEX SYSTEM 174' };
const RV_CONFIG_175 = { enabled: true, slot: 175, label: 'RED VORTEX SYSTEM 175' };
const RV_CONFIG_176 = { enabled: true, slot: 176, label: 'RED VORTEX SYSTEM 176' };
const RV_CONFIG_177 = { enabled: true, slot: 177, label: 'RED VORTEX SYSTEM 177' };
const RV_CONFIG_178 = { enabled: true, slot: 178, label: 'RED VORTEX SYSTEM 178' };
const RV_CONFIG_179 = { enabled: true, slot: 179, label: 'RED VORTEX SYSTEM 179' };
const RV_CONFIG_180 = { enabled: true, slot: 180, label: 'RED VORTEX SYSTEM 180' };
const RV_CONFIG_181 = { enabled: true, slot: 181, label: 'RED VORTEX SYSTEM 181' };
const RV_CONFIG_182 = { enabled: true, slot: 182, label: 'RED VORTEX SYSTEM 182' };
const RV_CONFIG_183 = { enabled: true, slot: 183, label: 'RED VORTEX SYSTEM 183' };
const RV_CONFIG_184 = { enabled: true, slot: 184, label: 'RED VORTEX SYSTEM 184' };
const RV_CONFIG_185 = { enabled: true, slot: 185, label: 'RED VORTEX SYSTEM 185' };
const RV_CONFIG_186 = { enabled: true, slot: 186, label: 'RED VORTEX SYSTEM 186' };
const RV_CONFIG_187 = { enabled: true, slot: 187, label: 'RED VORTEX SYSTEM 187' };
const RV_CONFIG_188 = { enabled: true, slot: 188, label: 'RED VORTEX SYSTEM 188' };
const RV_CONFIG_189 = { enabled: true, slot: 189, label: 'RED VORTEX SYSTEM 189' };
const RV_CONFIG_190 = { enabled: true, slot: 190, label: 'RED VORTEX SYSTEM 190' };
const RV_CONFIG_191 = { enabled: true, slot: 191, label: 'RED VORTEX SYSTEM 191' };
const RV_CONFIG_192 = { enabled: true, slot: 192, label: 'RED VORTEX SYSTEM 192' };
const RV_CONFIG_193 = { enabled: true, slot: 193, label: 'RED VORTEX SYSTEM 193' };
const RV_CONFIG_194 = { enabled: true, slot: 194, label: 'RED VORTEX SYSTEM 194' };
const RV_CONFIG_195 = { enabled: true, slot: 195, label: 'RED VORTEX SYSTEM 195' };
const RV_CONFIG_196 = { enabled: true, slot: 196, label: 'RED VORTEX SYSTEM 196' };
const RV_CONFIG_197 = { enabled: true, slot: 197, label: 'RED VORTEX SYSTEM 197' };
const RV_CONFIG_198 = { enabled: true, slot: 198, label: 'RED VORTEX SYSTEM 198' };
const RV_CONFIG_199 = { enabled: true, slot: 199, label: 'RED VORTEX SYSTEM 199' };
const RV_CONFIG_200 = { enabled: true, slot: 200, label: 'RED VORTEX SYSTEM 200' };
const RV_CONFIG_201 = { enabled: true, slot: 201, label: 'RED VORTEX SYSTEM 201' };
const RV_CONFIG_202 = { enabled: true, slot: 202, label: 'RED VORTEX SYSTEM 202' };
const RV_CONFIG_203 = { enabled: true, slot: 203, label: 'RED VORTEX SYSTEM 203' };
const RV_CONFIG_204 = { enabled: true, slot: 204, label: 'RED VORTEX SYSTEM 204' };
const RV_CONFIG_205 = { enabled: true, slot: 205, label: 'RED VORTEX SYSTEM 205' };
const RV_CONFIG_206 = { enabled: true, slot: 206, label: 'RED VORTEX SYSTEM 206' };
const RV_CONFIG_207 = { enabled: true, slot: 207, label: 'RED VORTEX SYSTEM 207' };
const RV_CONFIG_208 = { enabled: true, slot: 208, label: 'RED VORTEX SYSTEM 208' };
const RV_CONFIG_209 = { enabled: true, slot: 209, label: 'RED VORTEX SYSTEM 209' };
const RV_CONFIG_210 = { enabled: true, slot: 210, label: 'RED VORTEX SYSTEM 210' };
const RV_CONFIG_211 = { enabled: true, slot: 211, label: 'RED VORTEX SYSTEM 211' };
const RV_CONFIG_212 = { enabled: true, slot: 212, label: 'RED VORTEX SYSTEM 212' };
const RV_CONFIG_213 = { enabled: true, slot: 213, label: 'RED VORTEX SYSTEM 213' };
const RV_CONFIG_214 = { enabled: true, slot: 214, label: 'RED VORTEX SYSTEM 214' };
const RV_CONFIG_215 = { enabled: true, slot: 215, label: 'RED VORTEX SYSTEM 215' };
const RV_CONFIG_216 = { enabled: true, slot: 216, label: 'RED VORTEX SYSTEM 216' };
const RV_CONFIG_217 = { enabled: true, slot: 217, label: 'RED VORTEX SYSTEM 217' };
const RV_CONFIG_218 = { enabled: true, slot: 218, label: 'RED VORTEX SYSTEM 218' };
const RV_CONFIG_219 = { enabled: true, slot: 219, label: 'RED VORTEX SYSTEM 219' };
const RV_CONFIG_220 = { enabled: true, slot: 220, label: 'RED VORTEX SYSTEM 220' };
const RV_CONFIG_221 = { enabled: true, slot: 221, label: 'RED VORTEX SYSTEM 221' };
const RV_CONFIG_222 = { enabled: true, slot: 222, label: 'RED VORTEX SYSTEM 222' };
const RV_CONFIG_223 = { enabled: true, slot: 223, label: 'RED VORTEX SYSTEM 223' };
const RV_CONFIG_224 = { enabled: true, slot: 224, label: 'RED VORTEX SYSTEM 224' };
const RV_CONFIG_225 = { enabled: true, slot: 225, label: 'RED VORTEX SYSTEM 225' };
const RV_CONFIG_226 = { enabled: true, slot: 226, label: 'RED VORTEX SYSTEM 226' };
const RV_CONFIG_227 = { enabled: true, slot: 227, label: 'RED VORTEX SYSTEM 227' };
const RV_CONFIG_228 = { enabled: true, slot: 228, label: 'RED VORTEX SYSTEM 228' };
const RV_CONFIG_229 = { enabled: true, slot: 229, label: 'RED VORTEX SYSTEM 229' };
const RV_CONFIG_230 = { enabled: true, slot: 230, label: 'RED VORTEX SYSTEM 230' };
const RV_CONFIG_231 = { enabled: true, slot: 231, label: 'RED VORTEX SYSTEM 231' };
const RV_CONFIG_232 = { enabled: true, slot: 232, label: 'RED VORTEX SYSTEM 232' };
const RV_CONFIG_233 = { enabled: true, slot: 233, label: 'RED VORTEX SYSTEM 233' };
const RV_CONFIG_234 = { enabled: true, slot: 234, label: 'RED VORTEX SYSTEM 234' };
const RV_CONFIG_235 = { enabled: true, slot: 235, label: 'RED VORTEX SYSTEM 235' };
const RV_CONFIG_236 = { enabled: true, slot: 236, label: 'RED VORTEX SYSTEM 236' };
const RV_CONFIG_237 = { enabled: true, slot: 237, label: 'RED VORTEX SYSTEM 237' };
const RV_CONFIG_238 = { enabled: true, slot: 238, label: 'RED VORTEX SYSTEM 238' };
const RV_CONFIG_239 = { enabled: true, slot: 239, label: 'RED VORTEX SYSTEM 239' };
const RV_CONFIG_240 = { enabled: true, slot: 240, label: 'RED VORTEX SYSTEM 240' };
const RV_CONFIG_241 = { enabled: true, slot: 241, label: 'RED VORTEX SYSTEM 241' };
const RV_CONFIG_242 = { enabled: true, slot: 242, label: 'RED VORTEX SYSTEM 242' };
const RV_CONFIG_243 = { enabled: true, slot: 243, label: 'RED VORTEX SYSTEM 243' };
const RV_CONFIG_244 = { enabled: true, slot: 244, label: 'RED VORTEX SYSTEM 244' };
const RV_CONFIG_245 = { enabled: true, slot: 245, label: 'RED VORTEX SYSTEM 245' };
const RV_CONFIG_246 = { enabled: true, slot: 246, label: 'RED VORTEX SYSTEM 246' };
const RV_CONFIG_247 = { enabled: true, slot: 247, label: 'RED VORTEX SYSTEM 247' };
const RV_CONFIG_248 = { enabled: true, slot: 248, label: 'RED VORTEX SYSTEM 248' };
const RV_CONFIG_249 = { enabled: true, slot: 249, label: 'RED VORTEX SYSTEM 249' };
const RV_CONFIG_250 = { enabled: true, slot: 250, label: 'RED VORTEX SYSTEM 250' };
const RV_CONFIG_251 = { enabled: true, slot: 251, label: 'RED VORTEX SYSTEM 251' };
const RV_CONFIG_252 = { enabled: true, slot: 252, label: 'RED VORTEX SYSTEM 252' };
const RV_CONFIG_253 = { enabled: true, slot: 253, label: 'RED VORTEX SYSTEM 253' };
const RV_CONFIG_254 = { enabled: true, slot: 254, label: 'RED VORTEX SYSTEM 254' };
const RV_CONFIG_255 = { enabled: true, slot: 255, label: 'RED VORTEX SYSTEM 255' };
const RV_CONFIG_256 = { enabled: true, slot: 256, label: 'RED VORTEX SYSTEM 256' };
const RV_CONFIG_257 = { enabled: true, slot: 257, label: 'RED VORTEX SYSTEM 257' };
const RV_CONFIG_258 = { enabled: true, slot: 258, label: 'RED VORTEX SYSTEM 258' };
const RV_CONFIG_259 = { enabled: true, slot: 259, label: 'RED VORTEX SYSTEM 259' };
const RV_CONFIG_260 = { enabled: true, slot: 260, label: 'RED VORTEX SYSTEM 260' };
const RV_CONFIG_261 = { enabled: true, slot: 261, label: 'RED VORTEX SYSTEM 261' };
const RV_CONFIG_262 = { enabled: true, slot: 262, label: 'RED VORTEX SYSTEM 262' };
const RV_CONFIG_263 = { enabled: true, slot: 263, label: 'RED VORTEX SYSTEM 263' };
const RV_CONFIG_264 = { enabled: true, slot: 264, label: 'RED VORTEX SYSTEM 264' };
const RV_CONFIG_265 = { enabled: true, slot: 265, label: 'RED VORTEX SYSTEM 265' };
const RV_CONFIG_266 = { enabled: true, slot: 266, label: 'RED VORTEX SYSTEM 266' };
const RV_CONFIG_267 = { enabled: true, slot: 267, label: 'RED VORTEX SYSTEM 267' };
const RV_CONFIG_268 = { enabled: true, slot: 268, label: 'RED VORTEX SYSTEM 268' };
const RV_CONFIG_269 = { enabled: true, slot: 269, label: 'RED VORTEX SYSTEM 269' };
const RV_CONFIG_270 = { enabled: true, slot: 270, label: 'RED VORTEX SYSTEM 270' };
const RV_CONFIG_271 = { enabled: true, slot: 271, label: 'RED VORTEX SYSTEM 271' };
const RV_CONFIG_272 = { enabled: true, slot: 272, label: 'RED VORTEX SYSTEM 272' };
const RV_CONFIG_273 = { enabled: true, slot: 273, label: 'RED VORTEX SYSTEM 273' };
const RV_CONFIG_274 = { enabled: true, slot: 274, label: 'RED VORTEX SYSTEM 274' };
const RV_CONFIG_275 = { enabled: true, slot: 275, label: 'RED VORTEX SYSTEM 275' };
const RV_CONFIG_276 = { enabled: true, slot: 276, label: 'RED VORTEX SYSTEM 276' };
const RV_CONFIG_277 = { enabled: true, slot: 277, label: 'RED VORTEX SYSTEM 277' };
const RV_CONFIG_278 = { enabled: true, slot: 278, label: 'RED VORTEX SYSTEM 278' };
const RV_CONFIG_279 = { enabled: true, slot: 279, label: 'RED VORTEX SYSTEM 279' };
const RV_CONFIG_280 = { enabled: true, slot: 280, label: 'RED VORTEX SYSTEM 280' };
const RV_CONFIG_281 = { enabled: true, slot: 281, label: 'RED VORTEX SYSTEM 281' };
const RV_CONFIG_282 = { enabled: true, slot: 282, label: 'RED VORTEX SYSTEM 282' };
const RV_CONFIG_283 = { enabled: true, slot: 283, label: 'RED VORTEX SYSTEM 283' };
const RV_CONFIG_284 = { enabled: true, slot: 284, label: 'RED VORTEX SYSTEM 284' };
const RV_CONFIG_285 = { enabled: true, slot: 285, label: 'RED VORTEX SYSTEM 285' };
const RV_CONFIG_286 = { enabled: true, slot: 286, label: 'RED VORTEX SYSTEM 286' };
const RV_CONFIG_287 = { enabled: true, slot: 287, label: 'RED VORTEX SYSTEM 287' };
const RV_CONFIG_288 = { enabled: true, slot: 288, label: 'RED VORTEX SYSTEM 288' };
const RV_CONFIG_289 = { enabled: true, slot: 289, label: 'RED VORTEX SYSTEM 289' };
const RV_CONFIG_290 = { enabled: true, slot: 290, label: 'RED VORTEX SYSTEM 290' };
const RV_CONFIG_291 = { enabled: true, slot: 291, label: 'RED VORTEX SYSTEM 291' };
const RV_CONFIG_292 = { enabled: true, slot: 292, label: 'RED VORTEX SYSTEM 292' };
const RV_CONFIG_293 = { enabled: true, slot: 293, label: 'RED VORTEX SYSTEM 293' };
const RV_CONFIG_294 = { enabled: true, slot: 294, label: 'RED VORTEX SYSTEM 294' };
const RV_CONFIG_295 = { enabled: true, slot: 295, label: 'RED VORTEX SYSTEM 295' };
const RV_CONFIG_296 = { enabled: true, slot: 296, label: 'RED VORTEX SYSTEM 296' };
const RV_CONFIG_297 = { enabled: true, slot: 297, label: 'RED VORTEX SYSTEM 297' };
const RV_CONFIG_298 = { enabled: true, slot: 298, label: 'RED VORTEX SYSTEM 298' };
const RV_CONFIG_299 = { enabled: true, slot: 299, label: 'RED VORTEX SYSTEM 299' };
const RV_CONFIG_300 = { enabled: true, slot: 300, label: 'RED VORTEX SYSTEM 300' };
const RV_CONFIG_301 = { enabled: true, slot: 301, label: 'RED VORTEX SYSTEM 301' };
const RV_CONFIG_302 = { enabled: true, slot: 302, label: 'RED VORTEX SYSTEM 302' };
const RV_CONFIG_303 = { enabled: true, slot: 303, label: 'RED VORTEX SYSTEM 303' };
const RV_CONFIG_304 = { enabled: true, slot: 304, label: 'RED VORTEX SYSTEM 304' };
const RV_CONFIG_305 = { enabled: true, slot: 305, label: 'RED VORTEX SYSTEM 305' };
const RV_CONFIG_306 = { enabled: true, slot: 306, label: 'RED VORTEX SYSTEM 306' };
const RV_CONFIG_307 = { enabled: true, slot: 307, label: 'RED VORTEX SYSTEM 307' };
const RV_CONFIG_308 = { enabled: true, slot: 308, label: 'RED VORTEX SYSTEM 308' };
const RV_CONFIG_309 = { enabled: true, slot: 309, label: 'RED VORTEX SYSTEM 309' };
const RV_CONFIG_310 = { enabled: true, slot: 310, label: 'RED VORTEX SYSTEM 310' };
const RV_CONFIG_311 = { enabled: true, slot: 311, label: 'RED VORTEX SYSTEM 311' };
const RV_CONFIG_312 = { enabled: true, slot: 312, label: 'RED VORTEX SYSTEM 312' };
const RV_CONFIG_313 = { enabled: true, slot: 313, label: 'RED VORTEX SYSTEM 313' };
const RV_CONFIG_314 = { enabled: true, slot: 314, label: 'RED VORTEX SYSTEM 314' };
const RV_CONFIG_315 = { enabled: true, slot: 315, label: 'RED VORTEX SYSTEM 315' };
const RV_CONFIG_316 = { enabled: true, slot: 316, label: 'RED VORTEX SYSTEM 316' };
const RV_CONFIG_317 = { enabled: true, slot: 317, label: 'RED VORTEX SYSTEM 317' };
const RV_CONFIG_318 = { enabled: true, slot: 318, label: 'RED VORTEX SYSTEM 318' };
const RV_CONFIG_319 = { enabled: true, slot: 319, label: 'RED VORTEX SYSTEM 319' };
const RV_CONFIG_320 = { enabled: true, slot: 320, label: 'RED VORTEX SYSTEM 320' };
const RV_CONFIG_321 = { enabled: true, slot: 321, label: 'RED VORTEX SYSTEM 321' };
const RV_CONFIG_322 = { enabled: true, slot: 322, label: 'RED VORTEX SYSTEM 322' };
const RV_CONFIG_323 = { enabled: true, slot: 323, label: 'RED VORTEX SYSTEM 323' };
const RV_CONFIG_324 = { enabled: true, slot: 324, label: 'RED VORTEX SYSTEM 324' };
const RV_CONFIG_325 = { enabled: true, slot: 325, label: 'RED VORTEX SYSTEM 325' };
const RV_CONFIG_326 = { enabled: true, slot: 326, label: 'RED VORTEX SYSTEM 326' };
const RV_CONFIG_327 = { enabled: true, slot: 327, label: 'RED VORTEX SYSTEM 327' };
const RV_CONFIG_328 = { enabled: true, slot: 328, label: 'RED VORTEX SYSTEM 328' };
const RV_CONFIG_329 = { enabled: true, slot: 329, label: 'RED VORTEX SYSTEM 329' };
const RV_CONFIG_330 = { enabled: true, slot: 330, label: 'RED VORTEX SYSTEM 330' };
const RV_CONFIG_331 = { enabled: true, slot: 331, label: 'RED VORTEX SYSTEM 331' };
const RV_CONFIG_332 = { enabled: true, slot: 332, label: 'RED VORTEX SYSTEM 332' };
const RV_CONFIG_333 = { enabled: true, slot: 333, label: 'RED VORTEX SYSTEM 333' };
const RV_CONFIG_334 = { enabled: true, slot: 334, label: 'RED VORTEX SYSTEM 334' };
const RV_CONFIG_335 = { enabled: true, slot: 335, label: 'RED VORTEX SYSTEM 335' };
const RV_CONFIG_336 = { enabled: true, slot: 336, label: 'RED VORTEX SYSTEM 336' };
const RV_CONFIG_337 = { enabled: true, slot: 337, label: 'RED VORTEX SYSTEM 337' };
const RV_CONFIG_338 = { enabled: true, slot: 338, label: 'RED VORTEX SYSTEM 338' };
const RV_CONFIG_339 = { enabled: true, slot: 339, label: 'RED VORTEX SYSTEM 339' };
const RV_CONFIG_340 = { enabled: true, slot: 340, label: 'RED VORTEX SYSTEM 340' };
const RV_CONFIG_341 = { enabled: true, slot: 341, label: 'RED VORTEX SYSTEM 341' };
const RV_CONFIG_342 = { enabled: true, slot: 342, label: 'RED VORTEX SYSTEM 342' };
const RV_CONFIG_343 = { enabled: true, slot: 343, label: 'RED VORTEX SYSTEM 343' };
const RV_CONFIG_344 = { enabled: true, slot: 344, label: 'RED VORTEX SYSTEM 344' };
const RV_CONFIG_345 = { enabled: true, slot: 345, label: 'RED VORTEX SYSTEM 345' };
const RV_CONFIG_346 = { enabled: true, slot: 346, label: 'RED VORTEX SYSTEM 346' };
const RV_CONFIG_347 = { enabled: true, slot: 347, label: 'RED VORTEX SYSTEM 347' };
const RV_CONFIG_348 = { enabled: true, slot: 348, label: 'RED VORTEX SYSTEM 348' };
const RV_CONFIG_349 = { enabled: true, slot: 349, label: 'RED VORTEX SYSTEM 349' };
const RV_CONFIG_350 = { enabled: true, slot: 350, label: 'RED VORTEX SYSTEM 350' };
const RV_CONFIG_351 = { enabled: true, slot: 351, label: 'RED VORTEX SYSTEM 351' };
const RV_CONFIG_352 = { enabled: true, slot: 352, label: 'RED VORTEX SYSTEM 352' };
const RV_CONFIG_353 = { enabled: true, slot: 353, label: 'RED VORTEX SYSTEM 353' };
const RV_CONFIG_354 = { enabled: true, slot: 354, label: 'RED VORTEX SYSTEM 354' };
const RV_CONFIG_355 = { enabled: true, slot: 355, label: 'RED VORTEX SYSTEM 355' };
const RV_CONFIG_356 = { enabled: true, slot: 356, label: 'RED VORTEX SYSTEM 356' };
const RV_CONFIG_357 = { enabled: true, slot: 357, label: 'RED VORTEX SYSTEM 357' };
const RV_CONFIG_358 = { enabled: true, slot: 358, label: 'RED VORTEX SYSTEM 358' };
const RV_CONFIG_359 = { enabled: true, slot: 359, label: 'RED VORTEX SYSTEM 359' };
const RV_CONFIG_360 = { enabled: true, slot: 360, label: 'RED VORTEX SYSTEM 360' };
const RV_CONFIG_361 = { enabled: true, slot: 361, label: 'RED VORTEX SYSTEM 361' };
const RV_CONFIG_362 = { enabled: true, slot: 362, label: 'RED VORTEX SYSTEM 362' };
const RV_CONFIG_363 = { enabled: true, slot: 363, label: 'RED VORTEX SYSTEM 363' };
const RV_CONFIG_364 = { enabled: true, slot: 364, label: 'RED VORTEX SYSTEM 364' };
const RV_CONFIG_365 = { enabled: true, slot: 365, label: 'RED VORTEX SYSTEM 365' };
const RV_CONFIG_366 = { enabled: true, slot: 366, label: 'RED VORTEX SYSTEM 366' };
const RV_CONFIG_367 = { enabled: true, slot: 367, label: 'RED VORTEX SYSTEM 367' };
const RV_CONFIG_368 = { enabled: true, slot: 368, label: 'RED VORTEX SYSTEM 368' };
const RV_CONFIG_369 = { enabled: true, slot: 369, label: 'RED VORTEX SYSTEM 369' };
const RV_CONFIG_370 = { enabled: true, slot: 370, label: 'RED VORTEX SYSTEM 370' };
const RV_CONFIG_371 = { enabled: true, slot: 371, label: 'RED VORTEX SYSTEM 371' };
const RV_CONFIG_372 = { enabled: true, slot: 372, label: 'RED VORTEX SYSTEM 372' };
const RV_CONFIG_373 = { enabled: true, slot: 373, label: 'RED VORTEX SYSTEM 373' };
const RV_CONFIG_374 = { enabled: true, slot: 374, label: 'RED VORTEX SYSTEM 374' };
const RV_CONFIG_375 = { enabled: true, slot: 375, label: 'RED VORTEX SYSTEM 375' };
const RV_CONFIG_376 = { enabled: true, slot: 376, label: 'RED VORTEX SYSTEM 376' };
const RV_CONFIG_377 = { enabled: true, slot: 377, label: 'RED VORTEX SYSTEM 377' };
const RV_CONFIG_378 = { enabled: true, slot: 378, label: 'RED VORTEX SYSTEM 378' };
const RV_CONFIG_379 = { enabled: true, slot: 379, label: 'RED VORTEX SYSTEM 379' };
const RV_CONFIG_380 = { enabled: true, slot: 380, label: 'RED VORTEX SYSTEM 380' };
const RV_CONFIG_381 = { enabled: true, slot: 381, label: 'RED VORTEX SYSTEM 381' };
const RV_CONFIG_382 = { enabled: true, slot: 382, label: 'RED VORTEX SYSTEM 382' };
const RV_CONFIG_383 = { enabled: true, slot: 383, label: 'RED VORTEX SYSTEM 383' };
const RV_CONFIG_384 = { enabled: true, slot: 384, label: 'RED VORTEX SYSTEM 384' };
const RV_CONFIG_385 = { enabled: true, slot: 385, label: 'RED VORTEX SYSTEM 385' };
const RV_CONFIG_386 = { enabled: true, slot: 386, label: 'RED VORTEX SYSTEM 386' };
const RV_CONFIG_387 = { enabled: true, slot: 387, label: 'RED VORTEX SYSTEM 387' };
const RV_CONFIG_388 = { enabled: true, slot: 388, label: 'RED VORTEX SYSTEM 388' };
const RV_CONFIG_389 = { enabled: true, slot: 389, label: 'RED VORTEX SYSTEM 389' };
const RV_CONFIG_390 = { enabled: true, slot: 390, label: 'RED VORTEX SYSTEM 390' };
const RV_CONFIG_391 = { enabled: true, slot: 391, label: 'RED VORTEX SYSTEM 391' };
const RV_CONFIG_392 = { enabled: true, slot: 392, label: 'RED VORTEX SYSTEM 392' };
const RV_CONFIG_393 = { enabled: true, slot: 393, label: 'RED VORTEX SYSTEM 393' };
const RV_CONFIG_394 = { enabled: true, slot: 394, label: 'RED VORTEX SYSTEM 394' };
const RV_CONFIG_395 = { enabled: true, slot: 395, label: 'RED VORTEX SYSTEM 395' };
const RV_CONFIG_396 = { enabled: true, slot: 396, label: 'RED VORTEX SYSTEM 396' };
const RV_CONFIG_397 = { enabled: true, slot: 397, label: 'RED VORTEX SYSTEM 397' };
const RV_CONFIG_398 = { enabled: true, slot: 398, label: 'RED VORTEX SYSTEM 398' };
const RV_CONFIG_399 = { enabled: true, slot: 399, label: 'RED VORTEX SYSTEM 399' };
const RV_CONFIG_400 = { enabled: true, slot: 400, label: 'RED VORTEX SYSTEM 400' };
const RV_CONFIG_401 = { enabled: true, slot: 401, label: 'RED VORTEX SYSTEM 401' };
const RV_CONFIG_402 = { enabled: true, slot: 402, label: 'RED VORTEX SYSTEM 402' };
const RV_CONFIG_403 = { enabled: true, slot: 403, label: 'RED VORTEX SYSTEM 403' };
const RV_CONFIG_404 = { enabled: true, slot: 404, label: 'RED VORTEX SYSTEM 404' };
const RV_CONFIG_405 = { enabled: true, slot: 405, label: 'RED VORTEX SYSTEM 405' };
const RV_CONFIG_406 = { enabled: true, slot: 406, label: 'RED VORTEX SYSTEM 406' };
const RV_CONFIG_407 = { enabled: true, slot: 407, label: 'RED VORTEX SYSTEM 407' };
const RV_CONFIG_408 = { enabled: true, slot: 408, label: 'RED VORTEX SYSTEM 408' };
const RV_CONFIG_409 = { enabled: true, slot: 409, label: 'RED VORTEX SYSTEM 409' };
const RV_CONFIG_410 = { enabled: true, slot: 410, label: 'RED VORTEX SYSTEM 410' };
const RV_CONFIG_411 = { enabled: true, slot: 411, label: 'RED VORTEX SYSTEM 411' };
const RV_CONFIG_412 = { enabled: true, slot: 412, label: 'RED VORTEX SYSTEM 412' };
const RV_CONFIG_413 = { enabled: true, slot: 413, label: 'RED VORTEX SYSTEM 413' };
const RV_CONFIG_414 = { enabled: true, slot: 414, label: 'RED VORTEX SYSTEM 414' };
const RV_CONFIG_415 = { enabled: true, slot: 415, label: 'RED VORTEX SYSTEM 415' };
const RV_CONFIG_416 = { enabled: true, slot: 416, label: 'RED VORTEX SYSTEM 416' };
const RV_CONFIG_417 = { enabled: true, slot: 417, label: 'RED VORTEX SYSTEM 417' };
const RV_CONFIG_418 = { enabled: true, slot: 418, label: 'RED VORTEX SYSTEM 418' };
const RV_CONFIG_419 = { enabled: true, slot: 419, label: 'RED VORTEX SYSTEM 419' };
const RV_CONFIG_420 = { enabled: true, slot: 420, label: 'RED VORTEX SYSTEM 420' };
const RV_CONFIG_421 = { enabled: true, slot: 421, label: 'RED VORTEX SYSTEM 421' };
const RV_CONFIG_422 = { enabled: true, slot: 422, label: 'RED VORTEX SYSTEM 422' };
const RV_CONFIG_423 = { enabled: true, slot: 423, label: 'RED VORTEX SYSTEM 423' };
const RV_CONFIG_424 = { enabled: true, slot: 424, label: 'RED VORTEX SYSTEM 424' };
const RV_CONFIG_425 = { enabled: true, slot: 425, label: 'RED VORTEX SYSTEM 425' };
const RV_CONFIG_426 = { enabled: true, slot: 426, label: 'RED VORTEX SYSTEM 426' };
const RV_CONFIG_427 = { enabled: true, slot: 427, label: 'RED VORTEX SYSTEM 427' };
const RV_CONFIG_428 = { enabled: true, slot: 428, label: 'RED VORTEX SYSTEM 428' };
const RV_CONFIG_429 = { enabled: true, slot: 429, label: 'RED VORTEX SYSTEM 429' };
const RV_CONFIG_430 = { enabled: true, slot: 430, label: 'RED VORTEX SYSTEM 430' };
const RV_CONFIG_431 = { enabled: true, slot: 431, label: 'RED VORTEX SYSTEM 431' };
const RV_CONFIG_432 = { enabled: true, slot: 432, label: 'RED VORTEX SYSTEM 432' };
const RV_CONFIG_433 = { enabled: true, slot: 433, label: 'RED VORTEX SYSTEM 433' };
const RV_CONFIG_434 = { enabled: true, slot: 434, label: 'RED VORTEX SYSTEM 434' };
const RV_CONFIG_435 = { enabled: true, slot: 435, label: 'RED VORTEX SYSTEM 435' };
const RV_CONFIG_436 = { enabled: true, slot: 436, label: 'RED VORTEX SYSTEM 436' };
const RV_CONFIG_437 = { enabled: true, slot: 437, label: 'RED VORTEX SYSTEM 437' };
const RV_CONFIG_438 = { enabled: true, slot: 438, label: 'RED VORTEX SYSTEM 438' };
const RV_CONFIG_439 = { enabled: true, slot: 439, label: 'RED VORTEX SYSTEM 439' };
const RV_CONFIG_440 = { enabled: true, slot: 440, label: 'RED VORTEX SYSTEM 440' };
const RV_CONFIG_441 = { enabled: true, slot: 441, label: 'RED VORTEX SYSTEM 441' };
const RV_CONFIG_442 = { enabled: true, slot: 442, label: 'RED VORTEX SYSTEM 442' };
const RV_CONFIG_443 = { enabled: true, slot: 443, label: 'RED VORTEX SYSTEM 443' };
const RV_CONFIG_444 = { enabled: true, slot: 444, label: 'RED VORTEX SYSTEM 444' };
const RV_CONFIG_445 = { enabled: true, slot: 445, label: 'RED VORTEX SYSTEM 445' };
const RV_CONFIG_446 = { enabled: true, slot: 446, label: 'RED VORTEX SYSTEM 446' };
const RV_CONFIG_447 = { enabled: true, slot: 447, label: 'RED VORTEX SYSTEM 447' };
const RV_CONFIG_448 = { enabled: true, slot: 448, label: 'RED VORTEX SYSTEM 448' };
const RV_CONFIG_449 = { enabled: true, slot: 449, label: 'RED VORTEX SYSTEM 449' };
const RV_CONFIG_450 = { enabled: true, slot: 450, label: 'RED VORTEX SYSTEM 450' };
const RV_CONFIG_451 = { enabled: true, slot: 451, label: 'RED VORTEX SYSTEM 451' };
const RV_CONFIG_452 = { enabled: true, slot: 452, label: 'RED VORTEX SYSTEM 452' };
const RV_CONFIG_453 = { enabled: true, slot: 453, label: 'RED VORTEX SYSTEM 453' };
const RV_CONFIG_454 = { enabled: true, slot: 454, label: 'RED VORTEX SYSTEM 454' };
const RV_CONFIG_455 = { enabled: true, slot: 455, label: 'RED VORTEX SYSTEM 455' };
const RV_CONFIG_456 = { enabled: true, slot: 456, label: 'RED VORTEX SYSTEM 456' };
const RV_CONFIG_457 = { enabled: true, slot: 457, label: 'RED VORTEX SYSTEM 457' };
const RV_CONFIG_458 = { enabled: true, slot: 458, label: 'RED VORTEX SYSTEM 458' };
const RV_CONFIG_459 = { enabled: true, slot: 459, label: 'RED VORTEX SYSTEM 459' };
const RV_CONFIG_460 = { enabled: true, slot: 460, label: 'RED VORTEX SYSTEM 460' };
const RV_CONFIG_461 = { enabled: true, slot: 461, label: 'RED VORTEX SYSTEM 461' };
const RV_CONFIG_462 = { enabled: true, slot: 462, label: 'RED VORTEX SYSTEM 462' };
const RV_CONFIG_463 = { enabled: true, slot: 463, label: 'RED VORTEX SYSTEM 463' };
const RV_CONFIG_464 = { enabled: true, slot: 464, label: 'RED VORTEX SYSTEM 464' };
const RV_CONFIG_465 = { enabled: true, slot: 465, label: 'RED VORTEX SYSTEM 465' };
const RV_CONFIG_466 = { enabled: true, slot: 466, label: 'RED VORTEX SYSTEM 466' };
const RV_CONFIG_467 = { enabled: true, slot: 467, label: 'RED VORTEX SYSTEM 467' };
const RV_CONFIG_468 = { enabled: true, slot: 468, label: 'RED VORTEX SYSTEM 468' };
const RV_CONFIG_469 = { enabled: true, slot: 469, label: 'RED VORTEX SYSTEM 469' };
const RV_CONFIG_470 = { enabled: true, slot: 470, label: 'RED VORTEX SYSTEM 470' };
const RV_CONFIG_471 = { enabled: true, slot: 471, label: 'RED VORTEX SYSTEM 471' };
const RV_CONFIG_472 = { enabled: true, slot: 472, label: 'RED VORTEX SYSTEM 472' };
const RV_CONFIG_473 = { enabled: true, slot: 473, label: 'RED VORTEX SYSTEM 473' };
const RV_CONFIG_474 = { enabled: true, slot: 474, label: 'RED VORTEX SYSTEM 474' };
const RV_CONFIG_475 = { enabled: true, slot: 475, label: 'RED VORTEX SYSTEM 475' };
const RV_CONFIG_476 = { enabled: true, slot: 476, label: 'RED VORTEX SYSTEM 476' };
const RV_CONFIG_477 = { enabled: true, slot: 477, label: 'RED VORTEX SYSTEM 477' };
const RV_CONFIG_478 = { enabled: true, slot: 478, label: 'RED VORTEX SYSTEM 478' };
const RV_CONFIG_479 = { enabled: true, slot: 479, label: 'RED VORTEX SYSTEM 479' };
const RV_CONFIG_480 = { enabled: true, slot: 480, label: 'RED VORTEX SYSTEM 480' };
const RV_CONFIG_481 = { enabled: true, slot: 481, label: 'RED VORTEX SYSTEM 481' };
const RV_CONFIG_482 = { enabled: true, slot: 482, label: 'RED VORTEX SYSTEM 482' };
const RV_CONFIG_483 = { enabled: true, slot: 483, label: 'RED VORTEX SYSTEM 483' };
const RV_CONFIG_484 = { enabled: true, slot: 484, label: 'RED VORTEX SYSTEM 484' };
const RV_CONFIG_485 = { enabled: true, slot: 485, label: 'RED VORTEX SYSTEM 485' };
const RV_CONFIG_486 = { enabled: true, slot: 486, label: 'RED VORTEX SYSTEM 486' };
const RV_CONFIG_487 = { enabled: true, slot: 487, label: 'RED VORTEX SYSTEM 487' };
const RV_CONFIG_488 = { enabled: true, slot: 488, label: 'RED VORTEX SYSTEM 488' };
const RV_CONFIG_489 = { enabled: true, slot: 489, label: 'RED VORTEX SYSTEM 489' };
const RV_CONFIG_490 = { enabled: true, slot: 490, label: 'RED VORTEX SYSTEM 490' };
const RV_CONFIG_491 = { enabled: true, slot: 491, label: 'RED VORTEX SYSTEM 491' };
const RV_CONFIG_492 = { enabled: true, slot: 492, label: 'RED VORTEX SYSTEM 492' };
const RV_CONFIG_493 = { enabled: true, slot: 493, label: 'RED VORTEX SYSTEM 493' };
const RV_CONFIG_494 = { enabled: true, slot: 494, label: 'RED VORTEX SYSTEM 494' };
const RV_CONFIG_495 = { enabled: true, slot: 495, label: 'RED VORTEX SYSTEM 495' };
const RV_CONFIG_496 = { enabled: true, slot: 496, label: 'RED VORTEX SYSTEM 496' };
const RV_CONFIG_497 = { enabled: true, slot: 497, label: 'RED VORTEX SYSTEM 497' };
const RV_CONFIG_498 = { enabled: true, slot: 498, label: 'RED VORTEX SYSTEM 498' };
const RV_CONFIG_499 = { enabled: true, slot: 499, label: 'RED VORTEX SYSTEM 499' };
const RV_CONFIG_500 = { enabled: true, slot: 500, label: 'RED VORTEX SYSTEM 500' };
const RV_CONFIG_501 = { enabled: true, slot: 501, label: 'RED VORTEX SYSTEM 501' };
const RV_CONFIG_502 = { enabled: true, slot: 502, label: 'RED VORTEX SYSTEM 502' };
const RV_CONFIG_503 = { enabled: true, slot: 503, label: 'RED VORTEX SYSTEM 503' };
const RV_CONFIG_504 = { enabled: true, slot: 504, label: 'RED VORTEX SYSTEM 504' };
const RV_CONFIG_505 = { enabled: true, slot: 505, label: 'RED VORTEX SYSTEM 505' };
const RV_CONFIG_506 = { enabled: true, slot: 506, label: 'RED VORTEX SYSTEM 506' };
const RV_CONFIG_507 = { enabled: true, slot: 507, label: 'RED VORTEX SYSTEM 507' };
const RV_CONFIG_508 = { enabled: true, slot: 508, label: 'RED VORTEX SYSTEM 508' };
const RV_CONFIG_509 = { enabled: true, slot: 509, label: 'RED VORTEX SYSTEM 509' };
const RV_CONFIG_510 = { enabled: true, slot: 510, label: 'RED VORTEX SYSTEM 510' };
const RV_CONFIG_511 = { enabled: true, slot: 511, label: 'RED VORTEX SYSTEM 511' };
const RV_CONFIG_512 = { enabled: true, slot: 512, label: 'RED VORTEX SYSTEM 512' };
const RV_CONFIG_513 = { enabled: true, slot: 513, label: 'RED VORTEX SYSTEM 513' };
const RV_CONFIG_514 = { enabled: true, slot: 514, label: 'RED VORTEX SYSTEM 514' };
const RV_CONFIG_515 = { enabled: true, slot: 515, label: 'RED VORTEX SYSTEM 515' };
const RV_CONFIG_516 = { enabled: true, slot: 516, label: 'RED VORTEX SYSTEM 516' };
const RV_CONFIG_517 = { enabled: true, slot: 517, label: 'RED VORTEX SYSTEM 517' };
const RV_CONFIG_518 = { enabled: true, slot: 518, label: 'RED VORTEX SYSTEM 518' };
const RV_CONFIG_519 = { enabled: true, slot: 519, label: 'RED VORTEX SYSTEM 519' };
const RV_CONFIG_520 = { enabled: true, slot: 520, label: 'RED VORTEX SYSTEM 520' };
const RV_CONFIG_521 = { enabled: true, slot: 521, label: 'RED VORTEX SYSTEM 521' };
const RV_CONFIG_522 = { enabled: true, slot: 522, label: 'RED VORTEX SYSTEM 522' };
const RV_CONFIG_523 = { enabled: true, slot: 523, label: 'RED VORTEX SYSTEM 523' };
const RV_CONFIG_524 = { enabled: true, slot: 524, label: 'RED VORTEX SYSTEM 524' };
const RV_CONFIG_525 = { enabled: true, slot: 525, label: 'RED VORTEX SYSTEM 525' };
const RV_CONFIG_526 = { enabled: true, slot: 526, label: 'RED VORTEX SYSTEM 526' };
const RV_CONFIG_527 = { enabled: true, slot: 527, label: 'RED VORTEX SYSTEM 527' };
const RV_CONFIG_528 = { enabled: true, slot: 528, label: 'RED VORTEX SYSTEM 528' };
const RV_CONFIG_529 = { enabled: true, slot: 529, label: 'RED VORTEX SYSTEM 529' };
const RV_CONFIG_530 = { enabled: true, slot: 530, label: 'RED VORTEX SYSTEM 530' };
const RV_CONFIG_531 = { enabled: true, slot: 531, label: 'RED VORTEX SYSTEM 531' };
const RV_CONFIG_532 = { enabled: true, slot: 532, label: 'RED VORTEX SYSTEM 532' };
const RV_CONFIG_533 = { enabled: true, slot: 533, label: 'RED VORTEX SYSTEM 533' };
const RV_CONFIG_534 = { enabled: true, slot: 534, label: 'RED VORTEX SYSTEM 534' };
const RV_CONFIG_535 = { enabled: true, slot: 535, label: 'RED VORTEX SYSTEM 535' };
const RV_CONFIG_536 = { enabled: true, slot: 536, label: 'RED VORTEX SYSTEM 536' };
const RV_CONFIG_537 = { enabled: true, slot: 537, label: 'RED VORTEX SYSTEM 537' };
const RV_CONFIG_538 = { enabled: true, slot: 538, label: 'RED VORTEX SYSTEM 538' };
const RV_CONFIG_539 = { enabled: true, slot: 539, label: 'RED VORTEX SYSTEM 539' };
const RV_CONFIG_540 = { enabled: true, slot: 540, label: 'RED VORTEX SYSTEM 540' };
const RV_CONFIG_541 = { enabled: true, slot: 541, label: 'RED VORTEX SYSTEM 541' };
const RV_CONFIG_542 = { enabled: true, slot: 542, label: 'RED VORTEX SYSTEM 542' };
const RV_CONFIG_543 = { enabled: true, slot: 543, label: 'RED VORTEX SYSTEM 543' };
const RV_CONFIG_544 = { enabled: true, slot: 544, label: 'RED VORTEX SYSTEM 544' };
const RV_CONFIG_545 = { enabled: true, slot: 545, label: 'RED VORTEX SYSTEM 545' };
const RV_CONFIG_546 = { enabled: true, slot: 546, label: 'RED VORTEX SYSTEM 546' };
const RV_CONFIG_547 = { enabled: true, slot: 547, label: 'RED VORTEX SYSTEM 547' };
const RV_CONFIG_548 = { enabled: true, slot: 548, label: 'RED VORTEX SYSTEM 548' };
const RV_CONFIG_549 = { enabled: true, slot: 549, label: 'RED VORTEX SYSTEM 549' };
const RV_CONFIG_550 = { enabled: true, slot: 550, label: 'RED VORTEX SYSTEM 550' };
const RV_CONFIG_551 = { enabled: true, slot: 551, label: 'RED VORTEX SYSTEM 551' };
const RV_CONFIG_552 = { enabled: true, slot: 552, label: 'RED VORTEX SYSTEM 552' };
const RV_CONFIG_553 = { enabled: true, slot: 553, label: 'RED VORTEX SYSTEM 553' };
const RV_CONFIG_554 = { enabled: true, slot: 554, label: 'RED VORTEX SYSTEM 554' };
const RV_CONFIG_555 = { enabled: true, slot: 555, label: 'RED VORTEX SYSTEM 555' };
const RV_CONFIG_556 = { enabled: true, slot: 556, label: 'RED VORTEX SYSTEM 556' };
const RV_CONFIG_557 = { enabled: true, slot: 557, label: 'RED VORTEX SYSTEM 557' };
const RV_CONFIG_558 = { enabled: true, slot: 558, label: 'RED VORTEX SYSTEM 558' };
const RV_CONFIG_559 = { enabled: true, slot: 559, label: 'RED VORTEX SYSTEM 559' };
const RV_CONFIG_560 = { enabled: true, slot: 560, label: 'RED VORTEX SYSTEM 560' };
const RV_CONFIG_561 = { enabled: true, slot: 561, label: 'RED VORTEX SYSTEM 561' };
const RV_CONFIG_562 = { enabled: true, slot: 562, label: 'RED VORTEX SYSTEM 562' };
const RV_CONFIG_563 = { enabled: true, slot: 563, label: 'RED VORTEX SYSTEM 563' };
const RV_CONFIG_564 = { enabled: true, slot: 564, label: 'RED VORTEX SYSTEM 564' };
const RV_CONFIG_565 = { enabled: true, slot: 565, label: 'RED VORTEX SYSTEM 565' };
const RV_CONFIG_566 = { enabled: true, slot: 566, label: 'RED VORTEX SYSTEM 566' };
const RV_CONFIG_567 = { enabled: true, slot: 567, label: 'RED VORTEX SYSTEM 567' };
const RV_CONFIG_568 = { enabled: true, slot: 568, label: 'RED VORTEX SYSTEM 568' };
const RV_CONFIG_569 = { enabled: true, slot: 569, label: 'RED VORTEX SYSTEM 569' };
const RV_CONFIG_570 = { enabled: true, slot: 570, label: 'RED VORTEX SYSTEM 570' };
const RV_CONFIG_571 = { enabled: true, slot: 571, label: 'RED VORTEX SYSTEM 571' };
const RV_CONFIG_572 = { enabled: true, slot: 572, label: 'RED VORTEX SYSTEM 572' };
const RV_CONFIG_573 = { enabled: true, slot: 573, label: 'RED VORTEX SYSTEM 573' };
const RV_CONFIG_574 = { enabled: true, slot: 574, label: 'RED VORTEX SYSTEM 574' };
const RV_CONFIG_575 = { enabled: true, slot: 575, label: 'RED VORTEX SYSTEM 575' };
const RV_CONFIG_576 = { enabled: true, slot: 576, label: 'RED VORTEX SYSTEM 576' };
const RV_CONFIG_577 = { enabled: true, slot: 577, label: 'RED VORTEX SYSTEM 577' };
const RV_CONFIG_578 = { enabled: true, slot: 578, label: 'RED VORTEX SYSTEM 578' };
const RV_CONFIG_579 = { enabled: true, slot: 579, label: 'RED VORTEX SYSTEM 579' };
const RV_CONFIG_580 = { enabled: true, slot: 580, label: 'RED VORTEX SYSTEM 580' };
const RV_CONFIG_581 = { enabled: true, slot: 581, label: 'RED VORTEX SYSTEM 581' };
const RV_CONFIG_582 = { enabled: true, slot: 582, label: 'RED VORTEX SYSTEM 582' };
const RV_CONFIG_583 = { enabled: true, slot: 583, label: 'RED VORTEX SYSTEM 583' };
const RV_CONFIG_584 = { enabled: true, slot: 584, label: 'RED VORTEX SYSTEM 584' };
const RV_CONFIG_585 = { enabled: true, slot: 585, label: 'RED VORTEX SYSTEM 585' };
const RV_CONFIG_586 = { enabled: true, slot: 586, label: 'RED VORTEX SYSTEM 586' };
const RV_CONFIG_587 = { enabled: true, slot: 587, label: 'RED VORTEX SYSTEM 587' };
const RV_CONFIG_588 = { enabled: true, slot: 588, label: 'RED VORTEX SYSTEM 588' };
const RV_CONFIG_589 = { enabled: true, slot: 589, label: 'RED VORTEX SYSTEM 589' };
const RV_CONFIG_590 = { enabled: true, slot: 590, label: 'RED VORTEX SYSTEM 590' };
const RV_CONFIG_591 = { enabled: true, slot: 591, label: 'RED VORTEX SYSTEM 591' };
const RV_CONFIG_592 = { enabled: true, slot: 592, label: 'RED VORTEX SYSTEM 592' };
const RV_CONFIG_593 = { enabled: true, slot: 593, label: 'RED VORTEX SYSTEM 593' };
const RV_CONFIG_594 = { enabled: true, slot: 594, label: 'RED VORTEX SYSTEM 594' };
const RV_CONFIG_595 = { enabled: true, slot: 595, label: 'RED VORTEX SYSTEM 595' };
const RV_CONFIG_596 = { enabled: true, slot: 596, label: 'RED VORTEX SYSTEM 596' };
const RV_CONFIG_597 = { enabled: true, slot: 597, label: 'RED VORTEX SYSTEM 597' };
const RV_CONFIG_598 = { enabled: true, slot: 598, label: 'RED VORTEX SYSTEM 598' };
const RV_CONFIG_599 = { enabled: true, slot: 599, label: 'RED VORTEX SYSTEM 599' };
const RV_CONFIG_600 = { enabled: true, slot: 600, label: 'RED VORTEX SYSTEM 600' };
const RV_CONFIG_601 = { enabled: true, slot: 601, label: 'RED VORTEX SYSTEM 601' };
const RV_CONFIG_602 = { enabled: true, slot: 602, label: 'RED VORTEX SYSTEM 602' };
const RV_CONFIG_603 = { enabled: true, slot: 603, label: 'RED VORTEX SYSTEM 603' };
const RV_CONFIG_604 = { enabled: true, slot: 604, label: 'RED VORTEX SYSTEM 604' };
const RV_CONFIG_605 = { enabled: true, slot: 605, label: 'RED VORTEX SYSTEM 605' };
const RV_CONFIG_606 = { enabled: true, slot: 606, label: 'RED VORTEX SYSTEM 606' };
const RV_CONFIG_607 = { enabled: true, slot: 607, label: 'RED VORTEX SYSTEM 607' };
const RV_CONFIG_608 = { enabled: true, slot: 608, label: 'RED VORTEX SYSTEM 608' };
const RV_CONFIG_609 = { enabled: true, slot: 609, label: 'RED VORTEX SYSTEM 609' };
const RV_CONFIG_610 = { enabled: true, slot: 610, label: 'RED VORTEX SYSTEM 610' };
const RV_CONFIG_611 = { enabled: true, slot: 611, label: 'RED VORTEX SYSTEM 611' };
const RV_CONFIG_612 = { enabled: true, slot: 612, label: 'RED VORTEX SYSTEM 612' };
const RV_CONFIG_613 = { enabled: true, slot: 613, label: 'RED VORTEX SYSTEM 613' };
const RV_CONFIG_614 = { enabled: true, slot: 614, label: 'RED VORTEX SYSTEM 614' };
const RV_CONFIG_615 = { enabled: true, slot: 615, label: 'RED VORTEX SYSTEM 615' };
const RV_CONFIG_616 = { enabled: true, slot: 616, label: 'RED VORTEX SYSTEM 616' };
const RV_CONFIG_617 = { enabled: true, slot: 617, label: 'RED VORTEX SYSTEM 617' };
const RV_CONFIG_618 = { enabled: true, slot: 618, label: 'RED VORTEX SYSTEM 618' };
const RV_CONFIG_619 = { enabled: true, slot: 619, label: 'RED VORTEX SYSTEM 619' };
const RV_CONFIG_620 = { enabled: true, slot: 620, label: 'RED VORTEX SYSTEM 620' };
const RV_CONFIG_621 = { enabled: true, slot: 621, label: 'RED VORTEX SYSTEM 621' };
const RV_CONFIG_622 = { enabled: true, slot: 622, label: 'RED VORTEX SYSTEM 622' };
const RV_CONFIG_623 = { enabled: true, slot: 623, label: 'RED VORTEX SYSTEM 623' };
const RV_CONFIG_624 = { enabled: true, slot: 624, label: 'RED VORTEX SYSTEM 624' };
const RV_CONFIG_625 = { enabled: true, slot: 625, label: 'RED VORTEX SYSTEM 625' };
const RV_CONFIG_626 = { enabled: true, slot: 626, label: 'RED VORTEX SYSTEM 626' };
const RV_CONFIG_627 = { enabled: true, slot: 627, label: 'RED VORTEX SYSTEM 627' };
const RV_CONFIG_628 = { enabled: true, slot: 628, label: 'RED VORTEX SYSTEM 628' };
const RV_CONFIG_629 = { enabled: true, slot: 629, label: 'RED VORTEX SYSTEM 629' };
const RV_CONFIG_630 = { enabled: true, slot: 630, label: 'RED VORTEX SYSTEM 630' };
const RV_CONFIG_631 = { enabled: true, slot: 631, label: 'RED VORTEX SYSTEM 631' };
const RV_CONFIG_632 = { enabled: true, slot: 632, label: 'RED VORTEX SYSTEM 632' };
const RV_CONFIG_633 = { enabled: true, slot: 633, label: 'RED VORTEX SYSTEM 633' };
const RV_CONFIG_634 = { enabled: true, slot: 634, label: 'RED VORTEX SYSTEM 634' };
const RV_CONFIG_635 = { enabled: true, slot: 635, label: 'RED VORTEX SYSTEM 635' };
const RV_CONFIG_636 = { enabled: true, slot: 636, label: 'RED VORTEX SYSTEM 636' };
const RV_CONFIG_637 = { enabled: true, slot: 637, label: 'RED VORTEX SYSTEM 637' };
const RV_CONFIG_638 = { enabled: true, slot: 638, label: 'RED VORTEX SYSTEM 638' };
const RV_CONFIG_639 = { enabled: true, slot: 639, label: 'RED VORTEX SYSTEM 639' };
const RV_CONFIG_640 = { enabled: true, slot: 640, label: 'RED VORTEX SYSTEM 640' };
const RV_CONFIG_641 = { enabled: true, slot: 641, label: 'RED VORTEX SYSTEM 641' };
const RV_CONFIG_642 = { enabled: true, slot: 642, label: 'RED VORTEX SYSTEM 642' };
const RV_CONFIG_643 = { enabled: true, slot: 643, label: 'RED VORTEX SYSTEM 643' };
const RV_CONFIG_644 = { enabled: true, slot: 644, label: 'RED VORTEX SYSTEM 644' };
const RV_CONFIG_645 = { enabled: true, slot: 645, label: 'RED VORTEX SYSTEM 645' };
const RV_CONFIG_646 = { enabled: true, slot: 646, label: 'RED VORTEX SYSTEM 646' };
const RV_CONFIG_647 = { enabled: true, slot: 647, label: 'RED VORTEX SYSTEM 647' };
const RV_CONFIG_648 = { enabled: true, slot: 648, label: 'RED VORTEX SYSTEM 648' };
const RV_CONFIG_649 = { enabled: true, slot: 649, label: 'RED VORTEX SYSTEM 649' };
const RV_CONFIG_650 = { enabled: true, slot: 650, label: 'RED VORTEX SYSTEM 650' };
const RV_CONFIG_651 = { enabled: true, slot: 651, label: 'RED VORTEX SYSTEM 651' };
const RV_CONFIG_652 = { enabled: true, slot: 652, label: 'RED VORTEX SYSTEM 652' };
const RV_CONFIG_653 = { enabled: true, slot: 653, label: 'RED VORTEX SYSTEM 653' };
const RV_CONFIG_654 = { enabled: true, slot: 654, label: 'RED VORTEX SYSTEM 654' };
const RV_CONFIG_655 = { enabled: true, slot: 655, label: 'RED VORTEX SYSTEM 655' };
const RV_CONFIG_656 = { enabled: true, slot: 656, label: 'RED VORTEX SYSTEM 656' };
const RV_CONFIG_657 = { enabled: true, slot: 657, label: 'RED VORTEX SYSTEM 657' };
const RV_CONFIG_658 = { enabled: true, slot: 658, label: 'RED VORTEX SYSTEM 658' };
const RV_CONFIG_659 = { enabled: true, slot: 659, label: 'RED VORTEX SYSTEM 659' };
const RV_CONFIG_660 = { enabled: true, slot: 660, label: 'RED VORTEX SYSTEM 660' };
const RV_CONFIG_661 = { enabled: true, slot: 661, label: 'RED VORTEX SYSTEM 661' };
const RV_CONFIG_662 = { enabled: true, slot: 662, label: 'RED VORTEX SYSTEM 662' };
const RV_CONFIG_663 = { enabled: true, slot: 663, label: 'RED VORTEX SYSTEM 663' };
const RV_CONFIG_664 = { enabled: true, slot: 664, label: 'RED VORTEX SYSTEM 664' };
const RV_CONFIG_665 = { enabled: true, slot: 665, label: 'RED VORTEX SYSTEM 665' };
const RV_CONFIG_666 = { enabled: true, slot: 666, label: 'RED VORTEX SYSTEM 666' };
const RV_CONFIG_667 = { enabled: true, slot: 667, label: 'RED VORTEX SYSTEM 667' };
const RV_CONFIG_668 = { enabled: true, slot: 668, label: 'RED VORTEX SYSTEM 668' };
const RV_CONFIG_669 = { enabled: true, slot: 669, label: 'RED VORTEX SYSTEM 669' };
const RV_CONFIG_670 = { enabled: true, slot: 670, label: 'RED VORTEX SYSTEM 670' };
const RV_CONFIG_671 = { enabled: true, slot: 671, label: 'RED VORTEX SYSTEM 671' };
const RV_CONFIG_672 = { enabled: true, slot: 672, label: 'RED VORTEX SYSTEM 672' };
const RV_CONFIG_673 = { enabled: true, slot: 673, label: 'RED VORTEX SYSTEM 673' };
const RV_CONFIG_674 = { enabled: true, slot: 674, label: 'RED VORTEX SYSTEM 674' };
const RV_CONFIG_675 = { enabled: true, slot: 675, label: 'RED VORTEX SYSTEM 675' };
const RV_CONFIG_676 = { enabled: true, slot: 676, label: 'RED VORTEX SYSTEM 676' };
const RV_CONFIG_677 = { enabled: true, slot: 677, label: 'RED VORTEX SYSTEM 677' };
const RV_CONFIG_678 = { enabled: true, slot: 678, label: 'RED VORTEX SYSTEM 678' };
const RV_CONFIG_679 = { enabled: true, slot: 679, label: 'RED VORTEX SYSTEM 679' };
const RV_CONFIG_680 = { enabled: true, slot: 680, label: 'RED VORTEX SYSTEM 680' };
const RV_CONFIG_681 = { enabled: true, slot: 681, label: 'RED VORTEX SYSTEM 681' };
const RV_CONFIG_682 = { enabled: true, slot: 682, label: 'RED VORTEX SYSTEM 682' };
const RV_CONFIG_683 = { enabled: true, slot: 683, label: 'RED VORTEX SYSTEM 683' };
const RV_CONFIG_684 = { enabled: true, slot: 684, label: 'RED VORTEX SYSTEM 684' };
const RV_CONFIG_685 = { enabled: true, slot: 685, label: 'RED VORTEX SYSTEM 685' };
const RV_CONFIG_686 = { enabled: true, slot: 686, label: 'RED VORTEX SYSTEM 686' };
const RV_CONFIG_687 = { enabled: true, slot: 687, label: 'RED VORTEX SYSTEM 687' };
const RV_CONFIG_688 = { enabled: true, slot: 688, label: 'RED VORTEX SYSTEM 688' };
const RV_CONFIG_689 = { enabled: true, slot: 689, label: 'RED VORTEX SYSTEM 689' };
const RV_CONFIG_690 = { enabled: true, slot: 690, label: 'RED VORTEX SYSTEM 690' };
const RV_CONFIG_691 = { enabled: true, slot: 691, label: 'RED VORTEX SYSTEM 691' };
const RV_CONFIG_692 = { enabled: true, slot: 692, label: 'RED VORTEX SYSTEM 692' };
const RV_CONFIG_693 = { enabled: true, slot: 693, label: 'RED VORTEX SYSTEM 693' };
const RV_CONFIG_694 = { enabled: true, slot: 694, label: 'RED VORTEX SYSTEM 694' };
const RV_CONFIG_695 = { enabled: true, slot: 695, label: 'RED VORTEX SYSTEM 695' };
const RV_CONFIG_696 = { enabled: true, slot: 696, label: 'RED VORTEX SYSTEM 696' };
const RV_CONFIG_697 = { enabled: true, slot: 697, label: 'RED VORTEX SYSTEM 697' };
const RV_CONFIG_698 = { enabled: true, slot: 698, label: 'RED VORTEX SYSTEM 698' };
const RV_CONFIG_699 = { enabled: true, slot: 699, label: 'RED VORTEX SYSTEM 699' };
const RV_CONFIG_700 = { enabled: true, slot: 700, label: 'RED VORTEX SYSTEM 700' };
const RV_CONFIG_701 = { enabled: true, slot: 701, label: 'RED VORTEX SYSTEM 701' };
const RV_CONFIG_702 = { enabled: true, slot: 702, label: 'RED VORTEX SYSTEM 702' };
const RV_CONFIG_703 = { enabled: true, slot: 703, label: 'RED VORTEX SYSTEM 703' };
const RV_CONFIG_704 = { enabled: true, slot: 704, label: 'RED VORTEX SYSTEM 704' };
const RV_CONFIG_705 = { enabled: true, slot: 705, label: 'RED VORTEX SYSTEM 705' };
const RV_CONFIG_706 = { enabled: true, slot: 706, label: 'RED VORTEX SYSTEM 706' };
const RV_CONFIG_707 = { enabled: true, slot: 707, label: 'RED VORTEX SYSTEM 707' };
const RV_CONFIG_708 = { enabled: true, slot: 708, label: 'RED VORTEX SYSTEM 708' };
const RV_CONFIG_709 = { enabled: true, slot: 709, label: 'RED VORTEX SYSTEM 709' };
const RV_CONFIG_710 = { enabled: true, slot: 710, label: 'RED VORTEX SYSTEM 710' };
const RV_CONFIG_711 = { enabled: true, slot: 711, label: 'RED VORTEX SYSTEM 711' };
const RV_CONFIG_712 = { enabled: true, slot: 712, label: 'RED VORTEX SYSTEM 712' };
const RV_CONFIG_713 = { enabled: true, slot: 713, label: 'RED VORTEX SYSTEM 713' };
const RV_CONFIG_714 = { enabled: true, slot: 714, label: 'RED VORTEX SYSTEM 714' };
const RV_CONFIG_715 = { enabled: true, slot: 715, label: 'RED VORTEX SYSTEM 715' };
const RV_CONFIG_716 = { enabled: true, slot: 716, label: 'RED VORTEX SYSTEM 716' };
const RV_CONFIG_717 = { enabled: true, slot: 717, label: 'RED VORTEX SYSTEM 717' };
const RV_CONFIG_718 = { enabled: true, slot: 718, label: 'RED VORTEX SYSTEM 718' };
const RV_CONFIG_719 = { enabled: true, slot: 719, label: 'RED VORTEX SYSTEM 719' };
const RV_CONFIG_720 = { enabled: true, slot: 720, label: 'RED VORTEX SYSTEM 720' };
const RV_CONFIG_721 = { enabled: true, slot: 721, label: 'RED VORTEX SYSTEM 721' };
const RV_CONFIG_722 = { enabled: true, slot: 722, label: 'RED VORTEX SYSTEM 722' };
const RV_CONFIG_723 = { enabled: true, slot: 723, label: 'RED VORTEX SYSTEM 723' };
const RV_CONFIG_724 = { enabled: true, slot: 724, label: 'RED VORTEX SYSTEM 724' };
const RV_CONFIG_725 = { enabled: true, slot: 725, label: 'RED VORTEX SYSTEM 725' };
const RV_CONFIG_726 = { enabled: true, slot: 726, label: 'RED VORTEX SYSTEM 726' };
const RV_CONFIG_727 = { enabled: true, slot: 727, label: 'RED VORTEX SYSTEM 727' };
const RV_CONFIG_728 = { enabled: true, slot: 728, label: 'RED VORTEX SYSTEM 728' };
const RV_CONFIG_729 = { enabled: true, slot: 729, label: 'RED VORTEX SYSTEM 729' };
const RV_CONFIG_730 = { enabled: true, slot: 730, label: 'RED VORTEX SYSTEM 730' };
const RV_CONFIG_731 = { enabled: true, slot: 731, label: 'RED VORTEX SYSTEM 731' };
const RV_CONFIG_732 = { enabled: true, slot: 732, label: 'RED VORTEX SYSTEM 732' };
const RV_CONFIG_733 = { enabled: true, slot: 733, label: 'RED VORTEX SYSTEM 733' };
const RV_CONFIG_734 = { enabled: true, slot: 734, label: 'RED VORTEX SYSTEM 734' };
const RV_CONFIG_735 = { enabled: true, slot: 735, label: 'RED VORTEX SYSTEM 735' };
const RV_CONFIG_736 = { enabled: true, slot: 736, label: 'RED VORTEX SYSTEM 736' };
const RV_CONFIG_737 = { enabled: true, slot: 737, label: 'RED VORTEX SYSTEM 737' };
const RV_CONFIG_738 = { enabled: true, slot: 738, label: 'RED VORTEX SYSTEM 738' };
const RV_CONFIG_739 = { enabled: true, slot: 739, label: 'RED VORTEX SYSTEM 739' };
const RV_CONFIG_740 = { enabled: true, slot: 740, label: 'RED VORTEX SYSTEM 740' };
const RV_CONFIG_741 = { enabled: true, slot: 741, label: 'RED VORTEX SYSTEM 741' };
const RV_CONFIG_742 = { enabled: true, slot: 742, label: 'RED VORTEX SYSTEM 742' };
const RV_CONFIG_743 = { enabled: true, slot: 743, label: 'RED VORTEX SYSTEM 743' };
const RV_CONFIG_744 = { enabled: true, slot: 744, label: 'RED VORTEX SYSTEM 744' };
const RV_CONFIG_745 = { enabled: true, slot: 745, label: 'RED VORTEX SYSTEM 745' };
const RV_CONFIG_746 = { enabled: true, slot: 746, label: 'RED VORTEX SYSTEM 746' };
const RV_CONFIG_747 = { enabled: true, slot: 747, label: 'RED VORTEX SYSTEM 747' };
const RV_CONFIG_748 = { enabled: true, slot: 748, label: 'RED VORTEX SYSTEM 748' };
const RV_CONFIG_749 = { enabled: true, slot: 749, label: 'RED VORTEX SYSTEM 749' };
const RV_CONFIG_750 = { enabled: true, slot: 750, label: 'RED VORTEX SYSTEM 750' };
const RV_CONFIG_751 = { enabled: true, slot: 751, label: 'RED VORTEX SYSTEM 751' };
const RV_CONFIG_752 = { enabled: true, slot: 752, label: 'RED VORTEX SYSTEM 752' };
const RV_CONFIG_753 = { enabled: true, slot: 753, label: 'RED VORTEX SYSTEM 753' };
const RV_CONFIG_754 = { enabled: true, slot: 754, label: 'RED VORTEX SYSTEM 754' };
const RV_CONFIG_755 = { enabled: true, slot: 755, label: 'RED VORTEX SYSTEM 755' };
const RV_CONFIG_756 = { enabled: true, slot: 756, label: 'RED VORTEX SYSTEM 756' };
const RV_CONFIG_757 = { enabled: true, slot: 757, label: 'RED VORTEX SYSTEM 757' };
const RV_CONFIG_758 = { enabled: true, slot: 758, label: 'RED VORTEX SYSTEM 758' };
const RV_CONFIG_759 = { enabled: true, slot: 759, label: 'RED VORTEX SYSTEM 759' };
const RV_CONFIG_760 = { enabled: true, slot: 760, label: 'RED VORTEX SYSTEM 760' };
const RV_CONFIG_761 = { enabled: true, slot: 761, label: 'RED VORTEX SYSTEM 761' };
const RV_CONFIG_762 = { enabled: true, slot: 762, label: 'RED VORTEX SYSTEM 762' };
const RV_CONFIG_763 = { enabled: true, slot: 763, label: 'RED VORTEX SYSTEM 763' };
const RV_CONFIG_764 = { enabled: true, slot: 764, label: 'RED VORTEX SYSTEM 764' };
const RV_CONFIG_765 = { enabled: true, slot: 765, label: 'RED VORTEX SYSTEM 765' };
const RV_CONFIG_766 = { enabled: true, slot: 766, label: 'RED VORTEX SYSTEM 766' };
const RV_CONFIG_767 = { enabled: true, slot: 767, label: 'RED VORTEX SYSTEM 767' };
const RV_CONFIG_768 = { enabled: true, slot: 768, label: 'RED VORTEX SYSTEM 768' };
const RV_CONFIG_769 = { enabled: true, slot: 769, label: 'RED VORTEX SYSTEM 769' };
const RV_CONFIG_770 = { enabled: true, slot: 770, label: 'RED VORTEX SYSTEM 770' };
const RV_CONFIG_771 = { enabled: true, slot: 771, label: 'RED VORTEX SYSTEM 771' };
const RV_CONFIG_772 = { enabled: true, slot: 772, label: 'RED VORTEX SYSTEM 772' };
const RV_CONFIG_773 = { enabled: true, slot: 773, label: 'RED VORTEX SYSTEM 773' };
const RV_CONFIG_774 = { enabled: true, slot: 774, label: 'RED VORTEX SYSTEM 774' };
const RV_CONFIG_775 = { enabled: true, slot: 775, label: 'RED VORTEX SYSTEM 775' };
const RV_CONFIG_776 = { enabled: true, slot: 776, label: 'RED VORTEX SYSTEM 776' };
const RV_CONFIG_777 = { enabled: true, slot: 777, label: 'RED VORTEX SYSTEM 777' };
const RV_CONFIG_778 = { enabled: true, slot: 778, label: 'RED VORTEX SYSTEM 778' };
const RV_CONFIG_779 = { enabled: true, slot: 779, label: 'RED VORTEX SYSTEM 779' };
const RV_CONFIG_780 = { enabled: true, slot: 780, label: 'RED VORTEX SYSTEM 780' };
const RV_CONFIG_781 = { enabled: true, slot: 781, label: 'RED VORTEX SYSTEM 781' };
const RV_CONFIG_782 = { enabled: true, slot: 782, label: 'RED VORTEX SYSTEM 782' };
const RV_CONFIG_783 = { enabled: true, slot: 783, label: 'RED VORTEX SYSTEM 783' };
const RV_CONFIG_784 = { enabled: true, slot: 784, label: 'RED VORTEX SYSTEM 784' };
const RV_CONFIG_785 = { enabled: true, slot: 785, label: 'RED VORTEX SYSTEM 785' };
const RV_CONFIG_786 = { enabled: true, slot: 786, label: 'RED VORTEX SYSTEM 786' };
const RV_CONFIG_787 = { enabled: true, slot: 787, label: 'RED VORTEX SYSTEM 787' };
const RV_CONFIG_788 = { enabled: true, slot: 788, label: 'RED VORTEX SYSTEM 788' };
const RV_CONFIG_789 = { enabled: true, slot: 789, label: 'RED VORTEX SYSTEM 789' };
const RV_CONFIG_790 = { enabled: true, slot: 790, label: 'RED VORTEX SYSTEM 790' };
const RV_CONFIG_791 = { enabled: true, slot: 791, label: 'RED VORTEX SYSTEM 791' };
const RV_CONFIG_792 = { enabled: true, slot: 792, label: 'RED VORTEX SYSTEM 792' };
const RV_CONFIG_793 = { enabled: true, slot: 793, label: 'RED VORTEX SYSTEM 793' };
const RV_CONFIG_794 = { enabled: true, slot: 794, label: 'RED VORTEX SYSTEM 794' };
const RV_CONFIG_795 = { enabled: true, slot: 795, label: 'RED VORTEX SYSTEM 795' };
const RV_CONFIG_796 = { enabled: true, slot: 796, label: 'RED VORTEX SYSTEM 796' };
const RV_CONFIG_797 = { enabled: true, slot: 797, label: 'RED VORTEX SYSTEM 797' };
const RV_CONFIG_798 = { enabled: true, slot: 798, label: 'RED VORTEX SYSTEM 798' };
const RV_CONFIG_799 = { enabled: true, slot: 799, label: 'RED VORTEX SYSTEM 799' };
const RV_CONFIG_800 = { enabled: true, slot: 800, label: 'RED VORTEX SYSTEM 800' };
